// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/solarwinds/swo-sdk-go/v1/models/components"
)

type GetWebsiteMonitorDetails struct {
	Error string `json:"error"`
}

func (o *GetWebsiteMonitorDetails) GetError() string {
	if o == nil {
		return ""
	}
	return o.Error
}

type GetWebsiteMonitorInnerError struct {
	Code       string `json:"code"`
	InnerError string `json:"innerError"`
}

func (o *GetWebsiteMonitorInnerError) GetCode() string {
	if o == nil {
		return ""
	}
	return o.Code
}

func (o *GetWebsiteMonitorInnerError) GetInnerError() string {
	if o == nil {
		return ""
	}
	return o.InnerError
}

// GetWebsiteMonitorResponseBody - The server could not understand the request due to invalid syntax.
type GetWebsiteMonitorResponseBody struct {
	Code       string                       `json:"code"`
	Message    string                       `json:"message"`
	Target     *string                      `json:"target,omitempty"`
	Details    []GetWebsiteMonitorDetails   `json:"details,omitempty"`
	InnerError *GetWebsiteMonitorInnerError `json:"innerError,omitempty"`
	HTTPMeta   components.HTTPMetadata      `json:"-"`
}

var _ error = &GetWebsiteMonitorResponseBody{}

func (e *GetWebsiteMonitorResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
