// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CloudAccountsAwsOrganisationalUnitRequest struct {
	// AWS Control Tower Management Account ID.
	MgmtAccountID string `json:"mgmtAccountId"`
	// Organisational Structure of the AWS Account.
	Structure []CloudAccountsAwsOrganisationalUnit `json:"structure"`
}

func (o *CloudAccountsAwsOrganisationalUnitRequest) GetMgmtAccountID() string {
	if o == nil {
		return ""
	}
	return o.MgmtAccountID
}

func (o *CloudAccountsAwsOrganisationalUnitRequest) GetStructure() []CloudAccountsAwsOrganisationalUnit {
	if o == nil {
		return []CloudAccountsAwsOrganisationalUnit{}
	}
	return o.Structure
}
