// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CommonTag struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (o *CommonTag) GetKey() string {
	if o == nil {
		return ""
	}
	return o.Key
}

func (o *CommonTag) GetValue() string {
	if o == nil {
		return ""
	}
	return o.Value
}
