// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CommonPageInfo struct {
	// Token for the previous page, or empty string if on the first page.
	PrevPage string `json:"prevPage"`
	// Token for the next page, or empty string if on the last page.
	NextPage string `json:"nextPage"`
}

func (o *CommonPageInfo) GetPrevPage() string {
	if o == nil {
		return ""
	}
	return o.PrevPage
}

func (o *CommonPageInfo) GetNextPage() string {
	if o == nil {
		return ""
	}
	return o.NextPage
}
