// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DboConfig struct {
	// Organization-level configuration options for database observability agents/plugins
	ConfigOptions []CommonKeyValuePair `json:"configOptions"`
}

func (o *DboConfig) GetConfigOptions() []CommonKeyValuePair {
	if o == nil {
		return []CommonKeyValuePair{}
	}
	return o.ConfigOptions
}
