// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DemCustomHeaders struct {
	// Name of a request header. Must contain only characters allowed by RFC: a-z, A-Z, 0-9, - and _.
	Name string `json:"name"`
	// Value of a request header.
	Value string `json:"value"`
}

func (o *DemCustomHeaders) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *DemCustomHeaders) GetValue() string {
	if o == nil {
		return ""
	}
	return o.Value
}
