// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"mockserver/internal/sdk/optionalnullable"
	"mockserver/internal/sdk/utils"
	"time"
)

// DemGetURIResponseStatus - Current availability status of the URI.
type DemGetURIResponseStatus string

const (
	DemGetURIResponseStatusUp          DemGetURIResponseStatus = "up"
	DemGetURIResponseStatusDown        DemGetURIResponseStatus = "down"
	DemGetURIResponseStatusPaused      DemGetURIResponseStatus = "paused"
	DemGetURIResponseStatusMaintenance DemGetURIResponseStatus = "maintenance"
	DemGetURIResponseStatusUnknown     DemGetURIResponseStatus = "unknown"
)

func (e DemGetURIResponseStatus) ToPointer() *DemGetURIResponseStatus {
	return &e
}
func (e *DemGetURIResponseStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "up":
		fallthrough
	case "down":
		fallthrough
	case "paused":
		fallthrough
	case "maintenance":
		fallthrough
	case "unknown":
		*e = DemGetURIResponseStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DemGetURIResponseStatus: %v", v)
	}
}

type DemGetURIResponse struct {
	// Unique identifier of the URI.
	ID string `json:"id"`
	// Entity type, always 'Uri'.
	Type string `json:"type"`
	// Current availability status of the URI.
	Status DemGetURIResponseStatus `json:"status"`
	//   Name of the URI, which must be unique within the organization.
	//   The name must also not contain any control characters, any white space other than space (U+0020), or any consecutive, leading or trailing spaces.
	Name string `json:"name"`
	// IP/domain address of the URI.
	IPOrDomain string `json:"ipOrDomain"`
	// Availability check tests configuration for the URI.
	AvailabilityCheckSettings DemURIAvailabilityCheckSettings `json:"availabilityCheckSettings"`
	// Entity tags. Tag is a key-value pair, where there may be only single tag value for the same key.
	Tags []CommonTag `json:"tags,omitempty"`
	// Time when the last outage started.
	LastOutageStartTime optionalnullable.OptionalNullable[time.Time] `json:"lastOutageStartTime,omitempty"`
	// Time when the last outage ended.
	LastOutageEndTime optionalnullable.OptionalNullable[time.Time] `json:"lastOutageEndTime,omitempty"`
	// Time when the last test was performed.
	LastTestTime optionalnullable.OptionalNullable[time.Time] `json:"lastTestTime,omitempty"`
	// Last time when a synthetic test failed.
	LastErrorTime optionalnullable.OptionalNullable[time.Time] `json:"lastErrorTime,omitempty"`
	// Response time from the last synthetic check in milliseconds.
	LastResponseTime optionalnullable.OptionalNullable[int] `json:"lastResponseTime,omitempty"`
}

func (d DemGetURIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DemGetURIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, []string{"id", "type", "status", "name", "ipOrDomain", "availabilityCheckSettings"}); err != nil {
		return err
	}
	return nil
}

func (o *DemGetURIResponse) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *DemGetURIResponse) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

func (o *DemGetURIResponse) GetStatus() DemGetURIResponseStatus {
	if o == nil {
		return DemGetURIResponseStatus("")
	}
	return o.Status
}

func (o *DemGetURIResponse) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *DemGetURIResponse) GetIPOrDomain() string {
	if o == nil {
		return ""
	}
	return o.IPOrDomain
}

func (o *DemGetURIResponse) GetAvailabilityCheckSettings() DemURIAvailabilityCheckSettings {
	if o == nil {
		return DemURIAvailabilityCheckSettings{}
	}
	return o.AvailabilityCheckSettings
}

func (o *DemGetURIResponse) GetTags() []CommonTag {
	if o == nil {
		return nil
	}
	return o.Tags
}

func (o *DemGetURIResponse) GetLastOutageStartTime() optionalnullable.OptionalNullable[time.Time] {
	if o == nil {
		return nil
	}
	return o.LastOutageStartTime
}

func (o *DemGetURIResponse) GetLastOutageEndTime() optionalnullable.OptionalNullable[time.Time] {
	if o == nil {
		return nil
	}
	return o.LastOutageEndTime
}

func (o *DemGetURIResponse) GetLastTestTime() optionalnullable.OptionalNullable[time.Time] {
	if o == nil {
		return nil
	}
	return o.LastTestTime
}

func (o *DemGetURIResponse) GetLastErrorTime() optionalnullable.OptionalNullable[time.Time] {
	if o == nil {
		return nil
	}
	return o.LastErrorTime
}

func (o *DemGetURIResponse) GetLastResponseTime() optionalnullable.OptionalNullable[int] {
	if o == nil {
		return nil
	}
	return o.LastResponseTime
}
