// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DemListProbesResponse struct {
	// Synthetic probes used to perform availability tests.
	Probes []DemProbe `json:"probes"`
}

func (o *DemListProbesResponse) GetProbes() []DemProbe {
	if o == nil {
		return []DemProbe{}
	}
	return o.Probes
}
