// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DemOrganizationSettingsInput struct {
	// Configure outage conditions for Website/URI entities.
	AvailabilityOutageConfiguration *DemOutageConfiguration `json:"availabilityOutageConfiguration,omitempty"`
	// Configure outage conditions for Synthetic Transaction entities.
	TransactionOutageConfiguration *DemOutageConfiguration `json:"transactionOutageConfiguration,omitempty"`
}

func (o *DemOrganizationSettingsInput) GetAvailabilityOutageConfiguration() *DemOutageConfiguration {
	if o == nil {
		return nil
	}
	return o.AvailabilityOutageConfiguration
}

func (o *DemOrganizationSettingsInput) GetTransactionOutageConfiguration() *DemOutageConfiguration {
	if o == nil {
		return nil
	}
	return o.TransactionOutageConfiguration
}
