// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"mockserver/internal/sdk/utils"
	"time"
)

// DemOutageStatusStatus - Status of the outage
type DemOutageStatusStatus string

const (
	DemOutageStatusStatusUp          DemOutageStatusStatus = "up"
	DemOutageStatusStatusDown        DemOutageStatusStatus = "down"
	DemOutageStatusStatusMaintenance DemOutageStatusStatus = "maintenance"
	DemOutageStatusStatusPaused      DemOutageStatusStatus = "paused"
	DemOutageStatusStatusUnknown     DemOutageStatusStatus = "unknown"
)

func (e DemOutageStatusStatus) ToPointer() *DemOutageStatusStatus {
	return &e
}
func (e *DemOutageStatusStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "up":
		fallthrough
	case "down":
		fallthrough
	case "maintenance":
		fallthrough
	case "paused":
		fallthrough
	case "unknown":
		*e = DemOutageStatusStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DemOutageStatusStatus: %v", v)
	}
}

type DemOutageStatus struct {
	// Timestamp of the start of the outage
	StartTime time.Time `json:"startTime"`
	// Timestamp of the end of the outage
	EndTime time.Time `json:"endTime"`
	// Status of the outage
	Status DemOutageStatusStatus `json:"status"`
	// Reference to the result
	ResultID *string `json:"resultId,omitempty"`
	// Reference to the root cause analysis
	AnalysisID *string `json:"analysisId,omitempty"`
}

func (d DemOutageStatus) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DemOutageStatus) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, []string{"startTime", "endTime", "status"}); err != nil {
		return err
	}
	return nil
}

func (o *DemOutageStatus) GetStartTime() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.StartTime
}

func (o *DemOutageStatus) GetEndTime() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.EndTime
}

func (o *DemOutageStatus) GetStatus() DemOutageStatusStatus {
	if o == nil {
		return DemOutageStatusStatus("")
	}
	return o.Status
}

func (o *DemOutageStatus) GetResultID() *string {
	if o == nil {
		return nil
	}
	return o.ResultID
}

func (o *DemOutageStatus) GetAnalysisID() *string {
	if o == nil {
		return nil
	}
	return o.AnalysisID
}
