// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DemTransactionCommand struct {
	// Name of the transaction command.
	Command DemTransactionCommandName `json:"command"`
	// Target of the command, e.g. a URL to navigate to, or an element to interact with. All SIDE commands require a target, but some internal commands (e.g. "SWO_RESET") do not.
	Target *string `json:"target,omitempty"`
	// Human-readable representation of the target element. Usually derived from element's text content, alt attribute or id attribute. Must be omitted for commands that do not target elements ("OPEN", "PAUSE" etc.).
	DisplayText *string `json:"displayText,omitempty"`
	// Value of the command, e.g. a text to type into a text field. Most commands do not require value.
	Value *string `json:"value,omitempty"`
}

func (o *DemTransactionCommand) GetCommand() DemTransactionCommandName {
	if o == nil {
		return DemTransactionCommandName("")
	}
	return o.Command
}

func (o *DemTransactionCommand) GetTarget() *string {
	if o == nil {
		return nil
	}
	return o.Target
}

func (o *DemTransactionCommand) GetDisplayText() *string {
	if o == nil {
		return nil
	}
	return o.DisplayText
}

func (o *DemTransactionCommand) GetValue() *string {
	if o == nil {
		return nil
	}
	return o.Value
}
