// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// DemTestFromType - Specificity for location of synthetic probes to be used for availability tests.
type DemTestFromType string

const (
	DemTestFromTypeRegion  DemTestFromType = "REGION"
	DemTestFromTypeCountry DemTestFromType = "COUNTRY"
	DemTestFromTypeCity    DemTestFromType = "CITY"
)

func (e DemTestFromType) ToPointer() *DemTestFromType {
	return &e
}
func (e *DemTestFromType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "REGION":
		fallthrough
	case "COUNTRY":
		fallthrough
	case "CITY":
		*e = DemTestFromType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DemTestFromType: %v", v)
	}
}

type DemTestFrom struct {
	// Specificity for location of synthetic probes to be used for availability tests.
	Type DemTestFromType `json:"type"`
	// A list of probe location values of the selected type. At least one value matching an existing probe must be provided.
	Values []string `json:"values"`
}

func (o *DemTestFrom) GetType() DemTestFromType {
	if o == nil {
		return DemTestFromType("")
	}
	return o.Type
}

func (o *DemTestFrom) GetValues() []string {
	if o == nil {
		return []string{}
	}
	return o.Values
}
