// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"mockserver/internal/sdk/utils"
	"time"
)

// DemTestResultStatus - Status of the test result
type DemTestResultStatus string

const (
	DemTestResultStatusUp   DemTestResultStatus = "up"
	DemTestResultStatusDown DemTestResultStatus = "down"
)

func (e DemTestResultStatus) ToPointer() *DemTestResultStatus {
	return &e
}
func (e *DemTestResultStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "up":
		fallthrough
	case "down":
		*e = DemTestResultStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DemTestResultStatus: %v", v)
	}
}

// Phase - Indicates at which phase of the failure occurred
type Phase string

const (
	PhaseResolve    Phase = "resolve"
	PhaseConnection Phase = "connection"
	PhaseRequest    Phase = "request"
	PhaseResponse   Phase = "response"
	PhaseUnknown    Phase = "unknown"
)

func (e Phase) ToPointer() *Phase {
	return &e
}
func (e *Phase) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "resolve":
		fallthrough
	case "connection":
		fallthrough
	case "request":
		fallthrough
	case "response":
		fallthrough
	case "unknown":
		*e = Phase(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Phase: %v", v)
	}
}

type DemTestResult struct {
	// Timestamp of result
	Time time.Time `json:"time"`
	// Probe that produced the result
	Probe DemProbe `json:"probe"`
	// Response time in milliseconds
	ResponseTime int `json:"responseTime"`
	// Status of the test result
	Status DemTestResultStatus `json:"status"`
	// Indicates at which phase of the failure occurred
	Phase *Phase `json:"phase,omitempty"`
	// Short reason for failure
	Description *string `json:"description,omitempty"`
	// Longer reason for failure
	Message *string `json:"message,omitempty"`
	// Reference to the root cause analysis
	AnalysisID *string `json:"analysisId,omitempty"`
	// Reference to the validation
	ValidationsID *string `json:"validationsId,omitempty"`
}

func (d DemTestResult) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DemTestResult) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, []string{"time", "probe", "responseTime", "status"}); err != nil {
		return err
	}
	return nil
}

func (o *DemTestResult) GetTime() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.Time
}

func (o *DemTestResult) GetProbe() DemProbe {
	if o == nil {
		return DemProbe{}
	}
	return o.Probe
}

func (o *DemTestResult) GetResponseTime() int {
	if o == nil {
		return 0
	}
	return o.ResponseTime
}

func (o *DemTestResult) GetStatus() DemTestResultStatus {
	if o == nil {
		return DemTestResultStatus("")
	}
	return o.Status
}

func (o *DemTestResult) GetPhase() *Phase {
	if o == nil {
		return nil
	}
	return o.Phase
}

func (o *DemTestResult) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *DemTestResult) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *DemTestResult) GetAnalysisID() *string {
	if o == nil {
		return nil
	}
	return o.AnalysisID
}

func (o *DemTestResult) GetValidationsID() *string {
	if o == nil {
		return nil
	}
	return o.ValidationsID
}
