// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DemURI struct {
	// Name of the URI, which must be unique within the organization. The name must also not contain any control characters, any white space other than space (U+0020), or any consecutive, leading or trailing spaces.
	Name string `json:"name"`
	// IP/domain of the URI.
	IPOrDomain string `json:"ipOrDomain"`
	// Availability tests configuration for the URI.
	AvailabilityCheckSettings DemURIAvailabilityCheckSettingsInput `json:"availabilityCheckSettings"`
	// Tags associated with the URI for categorization.
	Tags []CommonTag `json:"tags,omitempty"`
}

func (o *DemURI) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *DemURI) GetIPOrDomain() string {
	if o == nil {
		return ""
	}
	return o.IPOrDomain
}

func (o *DemURI) GetAvailabilityCheckSettings() DemURIAvailabilityCheckSettingsInput {
	if o == nil {
		return DemURIAvailabilityCheckSettingsInput{}
	}
	return o.AvailabilityCheckSettings
}

func (o *DemURI) GetTags() []CommonTag {
	if o == nil {
		return nil
	}
	return o.Tags
}
