// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// DemURIAvailabilityCheckSettingsInputPlatformOptions - Configure cloud platforms of the synthetic availability test probes. If omitted or set to null, any available cloud platform may be chosen.
type DemURIAvailabilityCheckSettingsInputPlatformOptions struct {
	// Cloud platforms hosting synthetic probes.
	ProbePlatforms []DemProbePlatform `json:"probePlatforms"`
	//   Use this field to configure whether availability tests should be performed from all selected
	//   platforms or one randomly selected platform. It has no effect if you provided only one platform
	//   in the `probePlatforms` field.
	//
	//   If set to true, a separate test is made from each of the selected platforms.
	//
	//   If set to false, only one of the selected platforms is chosen every time.
	//
	//   If omitted, the previous setting will stay in effect. If there is no previous setting, the value
	//   will default to false.
	TestFromAll *bool `json:"testFromAll,omitempty"`
}

func (o *DemURIAvailabilityCheckSettingsInputPlatformOptions) GetProbePlatforms() []DemProbePlatform {
	if o == nil {
		return []DemProbePlatform{}
	}
	return o.ProbePlatforms
}

func (o *DemURIAvailabilityCheckSettingsInputPlatformOptions) GetTestFromAll() *bool {
	if o == nil {
		return nil
	}
	return o.TestFromAll
}

// DemURIAvailabilityCheckSettingsInputFailingTestLocations - How many locations must report a failure for an entity to be considered down.
type DemURIAvailabilityCheckSettingsInputFailingTestLocations string

const (
	DemURIAvailabilityCheckSettingsInputFailingTestLocationsAll DemURIAvailabilityCheckSettingsInputFailingTestLocations = "all"
	DemURIAvailabilityCheckSettingsInputFailingTestLocationsAny DemURIAvailabilityCheckSettingsInputFailingTestLocations = "any"
)

func (e DemURIAvailabilityCheckSettingsInputFailingTestLocations) ToPointer() *DemURIAvailabilityCheckSettingsInputFailingTestLocations {
	return &e
}
func (e *DemURIAvailabilityCheckSettingsInputFailingTestLocations) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "all":
		fallthrough
	case "any":
		*e = DemURIAvailabilityCheckSettingsInputFailingTestLocations(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DemURIAvailabilityCheckSettingsInputFailingTestLocations: %v", v)
	}
}

// DemURIAvailabilityCheckSettingsInputOutageConfiguration -   Default conditions when the entity is considered down.
//
//	If omitted or set to null, organization configuration will be used for this entity.
type DemURIAvailabilityCheckSettingsInputOutageConfiguration struct {
	// How many locations must report a failure for an entity to be considered down.
	FailingTestLocations DemURIAvailabilityCheckSettingsInputFailingTestLocations `json:"failingTestLocations"`
	// Number of consecutive failing tests for an entity to be considered down.
	ConsecutiveForDown int `json:"consecutiveForDown"`
}

func (o *DemURIAvailabilityCheckSettingsInputOutageConfiguration) GetFailingTestLocations() DemURIAvailabilityCheckSettingsInputFailingTestLocations {
	if o == nil {
		return DemURIAvailabilityCheckSettingsInputFailingTestLocations("")
	}
	return o.FailingTestLocations
}

func (o *DemURIAvailabilityCheckSettingsInputOutageConfiguration) GetConsecutiveForDown() int {
	if o == nil {
		return 0
	}
	return o.ConsecutiveForDown
}

// DemURIAvailabilityCheckSettingsInputDNS - DNS tests configuration for the URI. If omitted or set to null, DNS tests are disabled.
type DemURIAvailabilityCheckSettingsInputDNS struct {
	// Enables or disables DNS tests for the URI.
	// Exactly one test type (DNS, ping, TCP, or UDP) must be enabled for a URI.
	Enabled bool `json:"enabled"`
	// Nameserver to be used for DNS queries. Can be an IP address or domain name.
	Nameserver string `json:"nameserver"`
	// Port number to be used for DNS queries.
	Port *int `json:"port,omitempty"`
	// Expected IP address in DNS response.
	IPToExpect string `json:"ipToExpect"`
}

func (o *DemURIAvailabilityCheckSettingsInputDNS) GetEnabled() bool {
	if o == nil {
		return false
	}
	return o.Enabled
}

func (o *DemURIAvailabilityCheckSettingsInputDNS) GetNameserver() string {
	if o == nil {
		return ""
	}
	return o.Nameserver
}

func (o *DemURIAvailabilityCheckSettingsInputDNS) GetPort() *int {
	if o == nil {
		return nil
	}
	return o.Port
}

func (o *DemURIAvailabilityCheckSettingsInputDNS) GetIPToExpect() string {
	if o == nil {
		return ""
	}
	return o.IPToExpect
}

// DemURIAvailabilityCheckSettingsInputPing - Ping tests configuration for the URI. If omitted or set to null, ping tests are disabled.
type DemURIAvailabilityCheckSettingsInputPing struct {
	// Enables or disables ping tests for the URI.
	// Exactly one test type (DNS, ping, TCP, or UDP) must be enabled for a URI.
	Enabled bool `json:"enabled"`
}

func (o *DemURIAvailabilityCheckSettingsInputPing) GetEnabled() bool {
	if o == nil {
		return false
	}
	return o.Enabled
}

// DemURIAvailabilityCheckSettingsInputTCP - TCP tests configuration for the URI. If omitted or set to null, TCP tests are disabled.
type DemURIAvailabilityCheckSettingsInputTCP struct {
	// Enables or disables TCP tests for the URI.
	// Exactly one test type (DNS, ping, TCP, or UDP) must be enabled for a URI.
	Enabled bool `json:"enabled"`
	// Port number to be used in TCP tests.
	Port int `json:"port"`
	// String to send in the body of a TCP request.
	StringToSend *string `json:"stringToSend,omitempty"`
	// String to search for in the body of a TCP response.
	StringToExpect *string `json:"stringToExpect,omitempty"`
}

func (o *DemURIAvailabilityCheckSettingsInputTCP) GetEnabled() bool {
	if o == nil {
		return false
	}
	return o.Enabled
}

func (o *DemURIAvailabilityCheckSettingsInputTCP) GetPort() int {
	if o == nil {
		return 0
	}
	return o.Port
}

func (o *DemURIAvailabilityCheckSettingsInputTCP) GetStringToSend() *string {
	if o == nil {
		return nil
	}
	return o.StringToSend
}

func (o *DemURIAvailabilityCheckSettingsInputTCP) GetStringToExpect() *string {
	if o == nil {
		return nil
	}
	return o.StringToExpect
}

// DemURIAvailabilityCheckSettingsInputUDP - UDP tests configuration for the URI. If omitted or set to null, UDP tests are disabled.
type DemURIAvailabilityCheckSettingsInputUDP struct {
	// Enables or disables UDP tests for the URI.
	// Exactly one test type (DNS, ping, TCP, or UDP) must be enabled for a URI.
	Enabled bool `json:"enabled"`
	// Port number to be used in UDP tests.
	Port int `json:"port"`
	// String to send in the body of a UDP request.
	StringToSend string `json:"stringToSend"`
	// String to search for in the body of a UDP response.
	StringToExpect string `json:"stringToExpect"`
}

func (o *DemURIAvailabilityCheckSettingsInputUDP) GetEnabled() bool {
	if o == nil {
		return false
	}
	return o.Enabled
}

func (o *DemURIAvailabilityCheckSettingsInputUDP) GetPort() int {
	if o == nil {
		return 0
	}
	return o.Port
}

func (o *DemURIAvailabilityCheckSettingsInputUDP) GetStringToSend() string {
	if o == nil {
		return ""
	}
	return o.StringToSend
}

func (o *DemURIAvailabilityCheckSettingsInputUDP) GetStringToExpect() string {
	if o == nil {
		return ""
	}
	return o.StringToExpect
}

type DemURIAvailabilityCheckSettingsInput struct {
	// Configure cloud platforms of the synthetic availability test probes. If omitted or set to null, any available cloud platform may be chosen.
	PlatformOptions *DemURIAvailabilityCheckSettingsInputPlatformOptions `json:"platformOptions,omitempty"`
	//   Configure locations of the synthetic availability test probes.
	//   Acceptable values depend on the selected type and actual values of existing probes.
	TestFrom DemTestFrom `json:"testFrom"`
	// Configure how often availability tests should be performed. Provide a number of seconds that is one of 60, 300, 600, 900, 1800, 3600, 7200, 14400.
	TestIntervalInSeconds float64 `json:"testIntervalInSeconds"`
	//   Default conditions when the entity is considered down.
	//   If omitted or set to null, organization configuration will be used for this entity.
	OutageConfiguration *DemURIAvailabilityCheckSettingsInputOutageConfiguration `json:"outageConfiguration,omitempty"`
	// DNS tests configuration for the URI. If omitted or set to null, DNS tests are disabled.
	DNS *DemURIAvailabilityCheckSettingsInputDNS `json:"dns,omitempty"`
	// Ping tests configuration for the URI. If omitted or set to null, ping tests are disabled.
	Ping *DemURIAvailabilityCheckSettingsInputPing `json:"ping,omitempty"`
	// TCP tests configuration for the URI. If omitted or set to null, TCP tests are disabled.
	TCP *DemURIAvailabilityCheckSettingsInputTCP `json:"tcp,omitempty"`
	// UDP tests configuration for the URI. If omitted or set to null, UDP tests are disabled.
	UDP *DemURIAvailabilityCheckSettingsInputUDP `json:"udp,omitempty"`
}

func (o *DemURIAvailabilityCheckSettingsInput) GetPlatformOptions() *DemURIAvailabilityCheckSettingsInputPlatformOptions {
	if o == nil {
		return nil
	}
	return o.PlatformOptions
}

func (o *DemURIAvailabilityCheckSettingsInput) GetTestFrom() DemTestFrom {
	if o == nil {
		return DemTestFrom{}
	}
	return o.TestFrom
}

func (o *DemURIAvailabilityCheckSettingsInput) GetTestIntervalInSeconds() float64 {
	if o == nil {
		return 0.0
	}
	return o.TestIntervalInSeconds
}

func (o *DemURIAvailabilityCheckSettingsInput) GetOutageConfiguration() *DemURIAvailabilityCheckSettingsInputOutageConfiguration {
	if o == nil {
		return nil
	}
	return o.OutageConfiguration
}

func (o *DemURIAvailabilityCheckSettingsInput) GetDNS() *DemURIAvailabilityCheckSettingsInputDNS {
	if o == nil {
		return nil
	}
	return o.DNS
}

func (o *DemURIAvailabilityCheckSettingsInput) GetPing() *DemURIAvailabilityCheckSettingsInputPing {
	if o == nil {
		return nil
	}
	return o.Ping
}

func (o *DemURIAvailabilityCheckSettingsInput) GetTCP() *DemURIAvailabilityCheckSettingsInputTCP {
	if o == nil {
		return nil
	}
	return o.TCP
}

func (o *DemURIAvailabilityCheckSettingsInput) GetUDP() *DemURIAvailabilityCheckSettingsInputUDP {
	if o == nil {
		return nil
	}
	return o.UDP
}
