// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DemWindowSize struct {
	// Browser window width in pixels.
	Width int `json:"width"`
	// Browser window height in pixels.
	Height int `json:"height"`
}

func (o *DemWindowSize) GetWidth() int {
	if o == nil {
		return 0
	}
	return o.Width
}

func (o *DemWindowSize) GetHeight() int {
	if o == nil {
		return 0
	}
	return o.Height
}
