// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// IntegrationsArrayParameter - An array parameter: a named list of string values.
type IntegrationsArrayParameter struct {
	// Parameter name.
	Key string `json:"key"`
	// Ordered list of string values.
	Values []string `json:"values"`
}

func (o *IntegrationsArrayParameter) GetKey() string {
	if o == nil {
		return ""
	}
	return o.Key
}

func (o *IntegrationsArrayParameter) GetValues() []string {
	if o == nil {
		return []string{}
	}
	return o.Values
}
