// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// IntegrationsIntegration - A single integration instance.
type IntegrationsIntegration struct {
	// Stable public integration identifier sourced from the relevant pluginInstanceId. Read from GET responses and passed back on PATCH/DELETE.
	ID string `json:"id"`
	// Integration type, e.g. nginx or mysql.
	Type string `json:"type"`
	// User-visible display name.
	DisplayName *string `json:"displayName,omitempty"`
	// SWO Agent client ID.
	ClientID string `json:"clientId"`
	// Configuration parameters.
	Parameters []CommonKeyValuePair `json:"parameters"`
	// Array-valued configuration parameters.
	ArrayParameters []IntegrationsArrayParameter `json:"arrayParameters"`
	// Custom key-value attributes attached to integration metrics.
	Attributes []CommonKeyValuePair `json:"attributes"`
	// Credential references used for integration monitoring.
	CredentialsRefs []CommonKeyValuePair `json:"credentialsRefs"`
	// IDs of SWO entities matched for this integration instance. May contain multiple entries; empty when no entity exists.
	EntityIds []string `json:"entityIds,omitempty"`
}

func (o *IntegrationsIntegration) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *IntegrationsIntegration) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

func (o *IntegrationsIntegration) GetDisplayName() *string {
	if o == nil {
		return nil
	}
	return o.DisplayName
}

func (o *IntegrationsIntegration) GetClientID() string {
	if o == nil {
		return ""
	}
	return o.ClientID
}

func (o *IntegrationsIntegration) GetParameters() []CommonKeyValuePair {
	if o == nil {
		return []CommonKeyValuePair{}
	}
	return o.Parameters
}

func (o *IntegrationsIntegration) GetArrayParameters() []IntegrationsArrayParameter {
	if o == nil {
		return []IntegrationsArrayParameter{}
	}
	return o.ArrayParameters
}

func (o *IntegrationsIntegration) GetAttributes() []CommonKeyValuePair {
	if o == nil {
		return []CommonKeyValuePair{}
	}
	return o.Attributes
}

func (o *IntegrationsIntegration) GetCredentialsRefs() []CommonKeyValuePair {
	if o == nil {
		return []CommonKeyValuePair{}
	}
	return o.CredentialsRefs
}

func (o *IntegrationsIntegration) GetEntityIds() []string {
	if o == nil {
		return nil
	}
	return o.EntityIds
}
