// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/optionalnullable"
)

type MetricsUpdateCompositeMetricRequest struct {
	// Display name of the composite metric. A short description of the metric.
	DisplayName optionalnullable.OptionalNullable[string] `json:"displayName,omitempty"`
	// Description of the composite metric. A detailed description of the metric.
	Description optionalnullable.OptionalNullable[string] `json:"description,omitempty"`
	// PromQL query to calculate the composite metric.
	Formula string `json:"formula"`
	// Unit of the composite metric.
	Units optionalnullable.OptionalNullable[string] `json:"units,omitempty"`
}

func (o *MetricsUpdateCompositeMetricRequest) GetDisplayName() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.DisplayName
}

func (o *MetricsUpdateCompositeMetricRequest) GetDescription() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *MetricsUpdateCompositeMetricRequest) GetFormula() string {
	if o == nil {
		return ""
	}
	return o.Formula
}

func (o *MetricsUpdateCompositeMetricRequest) GetUnits() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Units
}
