// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type MetricsGrouping struct {
	// Attribute key-value pairs identifying this grouping.
	Attributes []CommonKeyValuePair `json:"attributes"`
	// An empty list indicates no data points are available.
	Measurements []MetricsMeasurement `json:"measurements"`
}

func (o *MetricsGrouping) GetAttributes() []CommonKeyValuePair {
	if o == nil {
		return []CommonKeyValuePair{}
	}
	return o.Attributes
}

func (o *MetricsGrouping) GetMeasurements() []MetricsMeasurement {
	if o == nil {
		return []MetricsMeasurement{}
	}
	return o.Measurements
}
