// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// OutageConfigurationFailingTestLocations - How many locations must report a failure for an entity to be considered down.
type OutageConfigurationFailingTestLocations string

const (
	OutageConfigurationFailingTestLocationsAll OutageConfigurationFailingTestLocations = "all"
	OutageConfigurationFailingTestLocationsAny OutageConfigurationFailingTestLocations = "any"
)

func (e OutageConfigurationFailingTestLocations) ToPointer() *OutageConfigurationFailingTestLocations {
	return &e
}
func (e *OutageConfigurationFailingTestLocations) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "all":
		fallthrough
	case "any":
		*e = OutageConfigurationFailingTestLocations(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OutageConfigurationFailingTestLocations: %v", v)
	}
}

type OutageConfiguration struct {
	// How many locations must report a failure for an entity to be considered down.
	FailingTestLocations OutageConfigurationFailingTestLocations `json:"failingTestLocations"`
	// Number of consecutive failing tests for an entity to be considered down.
	ConsecutiveForDown int `json:"consecutiveForDown"`
}

func (o *OutageConfiguration) GetFailingTestLocations() OutageConfigurationFailingTestLocations {
	if o == nil {
		return OutageConfigurationFailingTestLocations("")
	}
	return o.FailingTestLocations
}

func (o *OutageConfiguration) GetConsecutiveForDown() int {
	if o == nil {
		return 0
	}
	return o.ConsecutiveForDown
}
