// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// Tags to associate with the token.
type Tags struct {
	// Server tag value.
	Server string `json:"server"`
	// Tag without a value.
	TagWithoutValue string `json:"tag_without_value"`
}

func (o *Tags) GetServer() string {
	if o == nil {
		return ""
	}
	return o.Server
}

func (o *Tags) GetTagWithoutValue() string {
	if o == nil {
		return ""
	}
	return o.TagWithoutValue
}

// TokensCreateTokenRequestType - Type of token. Currently only 'ingestion' is supported.
type TokensCreateTokenRequestType string

const (
	TokensCreateTokenRequestTypeIngestion TokensCreateTokenRequestType = "ingestion"
)

func (e TokensCreateTokenRequestType) ToPointer() *TokensCreateTokenRequestType {
	return &e
}
func (e *TokensCreateTokenRequestType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ingestion":
		*e = TokensCreateTokenRequestType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TokensCreateTokenRequestType: %v", v)
	}
}

type TokensCreateTokenRequest struct {
	// Name of the token.
	Name string `json:"name"`
	// Tags to associate with the token.
	Tags Tags `json:"tags"`
	// Type of token. Currently only 'ingestion' is supported.
	Type TokensCreateTokenRequestType `json:"type"`
}

func (o *TokensCreateTokenRequest) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *TokensCreateTokenRequest) GetTags() Tags {
	if o == nil {
		return Tags{}
	}
	return o.Tags
}

func (o *TokensCreateTokenRequest) GetType() TokensCreateTokenRequestType {
	if o == nil {
		return TokensCreateTokenRequestType("")
	}
	return o.Type
}
