// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// URIAvailabilityCheckSettingsInputPlatformOptions - Configure cloud platforms of the synthetic availability test probes. If omitted or set to null, no particular cloud platform will be enforced.
type URIAvailabilityCheckSettingsInputPlatformOptions struct {
	// Cloud platforms hosting synthetic probes.
	ProbePlatforms []ProbePlatform `json:"probePlatforms"`
	//   Use this field to configure whether availability tests should be performed from all selected
	//   platforms or one randomly selected platform. It has no effect if you provided only one platform
	//   in the `probePlatforms` field.
	//
	//   If set to true, a separate test is made from each of the selected platforms.
	//
	//   If set to false, only one of the selected platforms is chosen every time.
	//
	//   If omitted, the previous setting will stay in effect. If there is no previous setting, the value
	//   will default to false.
	TestFromAll *bool `json:"testFromAll,omitempty"`
}

func (o *URIAvailabilityCheckSettingsInputPlatformOptions) GetProbePlatforms() []ProbePlatform {
	if o == nil {
		return []ProbePlatform{}
	}
	return o.ProbePlatforms
}

func (o *URIAvailabilityCheckSettingsInputPlatformOptions) GetTestFromAll() *bool {
	if o == nil {
		return nil
	}
	return o.TestFromAll
}

// URIAvailabilityCheckSettingsInputFailingTestLocations - How many locations must report a failure for an entity to be considered down.
type URIAvailabilityCheckSettingsInputFailingTestLocations string

const (
	URIAvailabilityCheckSettingsInputFailingTestLocationsAll URIAvailabilityCheckSettingsInputFailingTestLocations = "all"
	URIAvailabilityCheckSettingsInputFailingTestLocationsAny URIAvailabilityCheckSettingsInputFailingTestLocations = "any"
)

func (e URIAvailabilityCheckSettingsInputFailingTestLocations) ToPointer() *URIAvailabilityCheckSettingsInputFailingTestLocations {
	return &e
}
func (e *URIAvailabilityCheckSettingsInputFailingTestLocations) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "all":
		fallthrough
	case "any":
		*e = URIAvailabilityCheckSettingsInputFailingTestLocations(v)
		return nil
	default:
		return fmt.Errorf("invalid value for URIAvailabilityCheckSettingsInputFailingTestLocations: %v", v)
	}
}

// URIAvailabilityCheckSettingsInputOutageConfiguration -   Default conditions when the entity is considered down.
//
//	If omitted or set to null, organization configuration will be used for this entity.
type URIAvailabilityCheckSettingsInputOutageConfiguration struct {
	// How many locations must report a failure for an entity to be considered down.
	FailingTestLocations URIAvailabilityCheckSettingsInputFailingTestLocations `json:"failingTestLocations"`
	// Number of consecutive failing tests for an entity to be considered down.
	ConsecutiveForDown int `json:"consecutiveForDown"`
}

func (o *URIAvailabilityCheckSettingsInputOutageConfiguration) GetFailingTestLocations() URIAvailabilityCheckSettingsInputFailingTestLocations {
	if o == nil {
		return URIAvailabilityCheckSettingsInputFailingTestLocations("")
	}
	return o.FailingTestLocations
}

func (o *URIAvailabilityCheckSettingsInputOutageConfiguration) GetConsecutiveForDown() int {
	if o == nil {
		return 0
	}
	return o.ConsecutiveForDown
}

// URIAvailabilityCheckSettingsInputPing -   Use this field to configure ping tests for the URI. If omitted or set to null, ping tests will be disabled.
//
//	One test type (ping or TCP) must be enabled for a URI.
type URIAvailabilityCheckSettingsInputPing struct {
	// Use this field to configure ping tests for the URI. If omitted or set to false, ping tests will be disabled.
	// One test type (ping or TCP) must be enabled for a URI.
	Enabled bool `json:"enabled"`
}

func (o *URIAvailabilityCheckSettingsInputPing) GetEnabled() bool {
	if o == nil {
		return false
	}
	return o.Enabled
}

// URIAvailabilityCheckSettingsInputTCP -   Use this field to configure TCP tests for the URI. If omitted or set to null, TCP tests will be disabled.
//
//	One test type (ping or TCP) must be enabled for a URI.
type URIAvailabilityCheckSettingsInputTCP struct {
	// Use this field to configure TCP tests for the URI. If omitted or set to false, TCP tests will be disabled.
	// One test type (ping or TCP) must be enabled for a URI.
	Enabled bool `json:"enabled"`
	// Port number to be used in TCP tests.
	Port int `json:"port"`
	// Use this field to specify a string to send in the body of a TCP request.
	StringToSend *string `json:"stringToSend,omitempty"`
	// Use this field to specify a string to search for in the body of a TCP response.
	StringToExpect *string `json:"stringToExpect,omitempty"`
}

func (o *URIAvailabilityCheckSettingsInputTCP) GetEnabled() bool {
	if o == nil {
		return false
	}
	return o.Enabled
}

func (o *URIAvailabilityCheckSettingsInputTCP) GetPort() int {
	if o == nil {
		return 0
	}
	return o.Port
}

func (o *URIAvailabilityCheckSettingsInputTCP) GetStringToSend() *string {
	if o == nil {
		return nil
	}
	return o.StringToSend
}

func (o *URIAvailabilityCheckSettingsInputTCP) GetStringToExpect() *string {
	if o == nil {
		return nil
	}
	return o.StringToExpect
}

type URIAvailabilityCheckSettingsInput struct {
	// Configure cloud platforms of the synthetic availability test probes. If omitted or set to null, no particular cloud platform will be enforced.
	PlatformOptions *URIAvailabilityCheckSettingsInputPlatformOptions `json:"platformOptions,omitempty"`
	//   Configure locations of the synthetic availability test probes.
	//   Acceptable values depend on the selected type and actual values of existing probes.
	TestFrom TestFrom `json:"testFrom"`
	// Configure how often availability tests should be performed. Provide a number of seconds that is one of 60, 300, 600, 900, 1800, 3600, 7200, 14400.
	TestIntervalInSeconds float64 `json:"testIntervalInSeconds"`
	//   Default conditions when the entity is considered down.
	//   If omitted or set to null, organization configuration will be used for this entity.
	OutageConfiguration *URIAvailabilityCheckSettingsInputOutageConfiguration `json:"outageConfiguration,omitempty"`
	//   Use this field to configure ping tests for the URI. If omitted or set to null, ping tests will be disabled.
	//   One test type (ping or TCP) must be enabled for a URI.
	Ping *URIAvailabilityCheckSettingsInputPing `json:"ping,omitempty"`
	//   Use this field to configure TCP tests for the URI. If omitted or set to null, TCP tests will be disabled.
	//   One test type (ping or TCP) must be enabled for a URI.
	TCP *URIAvailabilityCheckSettingsInputTCP `json:"tcp,omitempty"`
}

func (o *URIAvailabilityCheckSettingsInput) GetPlatformOptions() *URIAvailabilityCheckSettingsInputPlatformOptions {
	if o == nil {
		return nil
	}
	return o.PlatformOptions
}

func (o *URIAvailabilityCheckSettingsInput) GetTestFrom() TestFrom {
	if o == nil {
		return TestFrom{}
	}
	return o.TestFrom
}

func (o *URIAvailabilityCheckSettingsInput) GetTestIntervalInSeconds() float64 {
	if o == nil {
		return 0.0
	}
	return o.TestIntervalInSeconds
}

func (o *URIAvailabilityCheckSettingsInput) GetOutageConfiguration() *URIAvailabilityCheckSettingsInputOutageConfiguration {
	if o == nil {
		return nil
	}
	return o.OutageConfiguration
}

func (o *URIAvailabilityCheckSettingsInput) GetPing() *URIAvailabilityCheckSettingsInputPing {
	if o == nil {
		return nil
	}
	return o.Ping
}

func (o *URIAvailabilityCheckSettingsInput) GetTCP() *URIAvailabilityCheckSettingsInputTCP {
	if o == nil {
		return nil
	}
	return o.TCP
}
