// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/solarwinds/swo-sdk-go/swov1/models/components"
)

type CreateTokenResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	TokensCreateTokenResponse *components.TokensCreateTokenResponse
}

func (o *CreateTokenResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateTokenResponse) GetTokensCreateTokenResponse() *components.TokensCreateTokenResponse {
	if o == nil {
		return nil
	}
	return o.TokensCreateTokenResponse
}
