// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/solarwinds/swo-sdk-go/swov1/models/components"
)

type DeleteIntegrationRequest struct {
	// Integration type, e.g. nginx or mysql.
	Type string `pathParam:"style=simple,explode=false,name=type"`
	// SWO Agent client ID.
	ClientID string `pathParam:"style=simple,explode=false,name=clientId"`
	// Integration ID (stable public identifier sourced from the relevant pluginInstanceId).
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Entity IDs to delete alongside the integration. Must be values from the integration's entityIds field. Omit to skip entity deletion.
	EntityIds []string `queryParam:"style=form,explode=true,name=entityIds"`
}

func (d *DeleteIntegrationRequest) GetType() string {
	if d == nil {
		return ""
	}
	return d.Type
}

func (d *DeleteIntegrationRequest) GetClientID() string {
	if d == nil {
		return ""
	}
	return d.ClientID
}

func (d *DeleteIntegrationRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *DeleteIntegrationRequest) GetEntityIds() []string {
	if d == nil {
		return nil
	}
	return d.EntityIds
}

type DeleteIntegrationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (d *DeleteIntegrationResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}
