// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/solarwinds/swo-sdk-go/swov1/models/components"
)

type DeleteWebsiteRequest struct {
	EntityID string `pathParam:"style=simple,explode=false,name=entityId"`
}

func (o *DeleteWebsiteRequest) GetEntityID() string {
	if o == nil {
		return ""
	}
	return o.EntityID
}

type DeleteWebsiteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	CommonEntityID *components.CommonEntityID
}

func (o *DeleteWebsiteResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DeleteWebsiteResponse) GetCommonEntityID() *components.CommonEntityID {
	if o == nil {
		return nil
	}
	return o.CommonEntityID
}
