// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/solarwinds/swo-sdk-go/swov1/models/components"
)

type ListIntegrationsByTypeRequest struct {
	// Integration type, e.g. nginx or mysql.
	Type string `pathParam:"style=simple,explode=false,name=type"`
	// Number of items in a response page. Default varies by API.
	PageSize *int `queryParam:"style=form,explode=false,name=pageSize"`
	// Token for the requested page.
	SkipToken *string `queryParam:"style=form,explode=false,name=skipToken"`
}

func (l *ListIntegrationsByTypeRequest) GetType() string {
	if l == nil {
		return ""
	}
	return l.Type
}

func (l *ListIntegrationsByTypeRequest) GetPageSize() *int {
	if l == nil {
		return nil
	}
	return l.PageSize
}

func (l *ListIntegrationsByTypeRequest) GetSkipToken() *string {
	if l == nil {
		return nil
	}
	return l.SkipToken
}

// ListIntegrationsByTypeResponseBody - The request has succeeded.
type ListIntegrationsByTypeResponseBody struct {
	// Integration instances of the requested type.
	Items []components.IntegrationsIntegration `json:"items"`
	// Pagination information.
	PageInfo components.CommonPageInfo `json:"pageInfo"`
}

func (l *ListIntegrationsByTypeResponseBody) GetItems() []components.IntegrationsIntegration {
	if l == nil {
		return []components.IntegrationsIntegration{}
	}
	return l.Items
}

func (l *ListIntegrationsByTypeResponseBody) GetPageInfo() components.CommonPageInfo {
	if l == nil {
		return components.CommonPageInfo{}
	}
	return l.PageInfo
}

type ListIntegrationsByTypeResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *ListIntegrationsByTypeResponseBody

	Next func() (*ListIntegrationsByTypeResponse, error)
}

func (l *ListIntegrationsByTypeResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListIntegrationsByTypeResponse) GetObject() *ListIntegrationsByTypeResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
