// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/solarwinds/swo-sdk-go/swov1/models/components"
)

type UpdateWebsiteMonitorRequest struct {
	EntityID string `pathParam:"style=simple,explode=false,name=entityId"`
	// The updated website monitoring configuration
	Website components.Website `request:"mediaType=application/json"`
}

func (o *UpdateWebsiteMonitorRequest) GetEntityID() string {
	if o == nil {
		return ""
	}
	return o.EntityID
}

func (o *UpdateWebsiteMonitorRequest) GetWebsite() components.Website {
	if o == nil {
		return components.Website{}
	}
	return o.Website
}

// UpdateWebsiteMonitorResponseBody - The request has succeeded.
type UpdateWebsiteMonitorResponseBody struct {
	ID string `json:"id"`
}

func (o *UpdateWebsiteMonitorResponseBody) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type UpdateWebsiteMonitorResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *UpdateWebsiteMonitorResponseBody
}

func (o *UpdateWebsiteMonitorResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateWebsiteMonitorResponse) GetObject() *UpdateWebsiteMonitorResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
