// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/solarwinds/swo-sdk-go/swov1/models/components"
)

type UpdateCompositeMetricRequest struct {
	// Metric name.
	Name string `pathParam:"style=simple,explode=false,name=name"`
	// Metric properties to update
	MetricsUpdateCompositeMetricRequest components.MetricsUpdateCompositeMetricRequest `request:"mediaType=application/json"`
}

func (o *UpdateCompositeMetricRequest) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *UpdateCompositeMetricRequest) GetMetricsUpdateCompositeMetricRequest() components.MetricsUpdateCompositeMetricRequest {
	if o == nil {
		return components.MetricsUpdateCompositeMetricRequest{}
	}
	return o.MetricsUpdateCompositeMetricRequest
}

type UpdateCompositeMetricResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	MetricsCompositeMetric *components.MetricsCompositeMetric
}

func (o *UpdateCompositeMetricResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateCompositeMetricResponse) GetMetricsCompositeMetric() *components.MetricsCompositeMetric {
	if o == nil {
		return nil
	}
	return o.MetricsCompositeMetric
}
