// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/solarwinds/swo-sdk-go/swov1/models/components"
)

type UpdateDatabaseRequest struct {
	EntityID                 string                              `pathParam:"style=simple,explode=false,name=entityId"`
	DboUpdateDatabaseRequest components.DboUpdateDatabaseRequest `request:"mediaType=application/json"`
}

func (o *UpdateDatabaseRequest) GetEntityID() string {
	if o == nil {
		return ""
	}
	return o.EntityID
}

func (o *UpdateDatabaseRequest) GetDboUpdateDatabaseRequest() components.DboUpdateDatabaseRequest {
	if o == nil {
		return components.DboUpdateDatabaseRequest{}
	}
	return o.DboUpdateDatabaseRequest
}

type UpdateDatabaseResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *UpdateDatabaseResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
