// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/solarwinds/swo-sdk-go/swov1/models/components"
)

type UpdateCompositeMetricRequest struct {
	// The metric name
	Name string `pathParam:"style=simple,explode=false,name=name"`
	// Metric properties to update
	UpdateCompositeMetric components.UpdateCompositeMetric `request:"mediaType=application/json"`
}

func (o *UpdateCompositeMetricRequest) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *UpdateCompositeMetricRequest) GetUpdateCompositeMetric() components.UpdateCompositeMetric {
	if o == nil {
		return components.UpdateCompositeMetric{}
	}
	return o.UpdateCompositeMetric
}

type UpdateCompositeMetricResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *UpdateCompositeMetricResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
