// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/solarwinds/swo-sdk-go/models/components"
)

type ListMetricsForEntityTypeRequest struct {
	Type string `pathParam:"style=simple,explode=false,name=type"`
	// Timestamp in ISO 8601 format in UTC timezone: yyyy-MM-ddTHH:mm:ssZ
	StartTime *string `queryParam:"style=form,explode=false,name=startTime"`
	// Timestamp in ISO 8601 format in UTC timezone: yyyy-MM-ddTHH:mm:ssZ
	EndTime *string `queryParam:"style=form,explode=false,name=endTime"`
}

func (o *ListMetricsForEntityTypeRequest) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

func (o *ListMetricsForEntityTypeRequest) GetStartTime() *string {
	if o == nil {
		return nil
	}
	return o.StartTime
}

func (o *ListMetricsForEntityTypeRequest) GetEndTime() *string {
	if o == nil {
		return nil
	}
	return o.EndTime
}

// ListMetricsForEntityTypeResponseBody - The request has succeeded.
type ListMetricsForEntityTypeResponseBody struct {
	Type    string                        `json:"type"`
	Metrics []components.CommonMetricInfo `json:"metrics"`
}

func (o *ListMetricsForEntityTypeResponseBody) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

func (o *ListMetricsForEntityTypeResponseBody) GetMetrics() []components.CommonMetricInfo {
	if o == nil {
		return []components.CommonMetricInfo{}
	}
	return o.Metrics
}

type ListMetricsForEntityTypeResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *ListMetricsForEntityTypeResponseBody
}

func (o *ListMetricsForEntityTypeResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListMetricsForEntityTypeResponse) GetObject() *ListMetricsForEntityTypeResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
