// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CheckForString struct {
	// Defines whether the check should pass only when the string is present on the page (CONTAINS) or only when it is absent (DOES_NOT_CONTAIN).
	Operator Operator `json:"operator"`
	// The string that which will be searched in the page source code.
	Value string `json:"value"`
}

func (o *CheckForString) GetOperator() Operator {
	if o == nil {
		return Operator("")
	}
	return o.Operator
}

func (o *CheckForString) GetValue() string {
	if o == nil {
		return ""
	}
	return o.Value
}
