// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/solarwinds/swo-sdk-go/swov1/models/components"
)

type CreateCompositeMetricMetricsDetails struct {
	Error string `json:"error"`
}

func (o *CreateCompositeMetricMetricsDetails) GetError() string {
	if o == nil {
		return ""
	}
	return o.Error
}

type CreateCompositeMetricMetricsInnerError struct {
	Code       string `json:"code"`
	InnerError string `json:"innerError"`
}

func (o *CreateCompositeMetricMetricsInnerError) GetCode() string {
	if o == nil {
		return ""
	}
	return o.Code
}

func (o *CreateCompositeMetricMetricsInnerError) GetInnerError() string {
	if o == nil {
		return ""
	}
	return o.InnerError
}

// CreateCompositeMetricMetricsResponseBody - Access is forbidden.
type CreateCompositeMetricMetricsResponseBody struct {
	Code       string                                  `json:"code"`
	Message    string                                  `json:"message"`
	Target     *string                                 `json:"target,omitempty"`
	Details    []CreateCompositeMetricMetricsDetails   `json:"details,omitempty"`
	InnerError *CreateCompositeMetricMetricsInnerError `json:"innerError,omitempty"`
	HTTPMeta   components.HTTPMetadata                 `json:"-"`
}

var _ error = &CreateCompositeMetricMetricsResponseBody{}

func (e *CreateCompositeMetricMetricsResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type CreateCompositeMetricDetails struct {
	Error string `json:"error"`
}

func (o *CreateCompositeMetricDetails) GetError() string {
	if o == nil {
		return ""
	}
	return o.Error
}

type CreateCompositeMetricInnerError struct {
	Code       string `json:"code"`
	InnerError string `json:"innerError"`
}

func (o *CreateCompositeMetricInnerError) GetCode() string {
	if o == nil {
		return ""
	}
	return o.Code
}

func (o *CreateCompositeMetricInnerError) GetInnerError() string {
	if o == nil {
		return ""
	}
	return o.InnerError
}

// CreateCompositeMetricResponseBody - The server could not understand the request due to invalid syntax.
type CreateCompositeMetricResponseBody struct {
	Code       string                           `json:"code"`
	Message    string                           `json:"message"`
	Target     *string                          `json:"target,omitempty"`
	Details    []CreateCompositeMetricDetails   `json:"details,omitempty"`
	InnerError *CreateCompositeMetricInnerError `json:"innerError,omitempty"`
	HTTPMeta   components.HTTPMetadata          `json:"-"`
}

var _ error = &CreateCompositeMetricResponseBody{}

func (e *CreateCompositeMetricResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
