// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/solarwinds/swo-sdk-go/swov1/models/components"
)

// DeleteCompositeMetricMetricsResponseBody - The server cannot find the requested resource.
type DeleteCompositeMetricMetricsResponseBody struct {
	// HTTP status code as defined in RFC 2817
	Code int64 `json:"code"`
	// Supporting description of the error
	Message  string                  `json:"message"`
	Target   *string                 `json:"target,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &DeleteCompositeMetricMetricsResponseBody{}

func (e *DeleteCompositeMetricMetricsResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// DeleteCompositeMetricResponseBody - Access is forbidden.
type DeleteCompositeMetricResponseBody struct {
	// HTTP status code as defined in RFC 2817
	Code int64 `json:"code"`
	// Supporting description of the error
	Message  string                  `json:"message"`
	Target   *string                 `json:"target,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &DeleteCompositeMetricResponseBody{}

func (e *DeleteCompositeMetricResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
