// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"fmt"
	"github.com/solarwinds/swo-sdk-go/swov1/models/components"
)

type GetMetricByNameCode string

const (
	GetMetricByNameCodeNotFound GetMetricByNameCode = "NotFound"
)

func (e GetMetricByNameCode) ToPointer() *GetMetricByNameCode {
	return &e
}
func (e *GetMetricByNameCode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "NotFound":
		*e = GetMetricByNameCode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetMetricByNameCode: %v", v)
	}
}

// GetMetricByNameResponseBody - The server cannot find the requested resource.
type GetMetricByNameResponseBody struct {
	Code     GetMetricByNameCode     `json:"code"`
	Message  string                  `json:"message"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &GetMetricByNameResponseBody{}

func (e *GetMetricByNameResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
