// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/solarwinds/swo-sdk-go/swov1/models/components"
)

// ListEntitiesEntitiesResponseBody - Access is unauthorized.
type ListEntitiesEntitiesResponseBody struct {
	// Supporting description of the error
	Message  string                  `json:"message"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &ListEntitiesEntitiesResponseBody{}

func (e *ListEntitiesEntitiesResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// ListEntitiesResponseBody - The server could not understand the request due to invalid syntax.
type ListEntitiesResponseBody struct {
	// Supporting description of the error
	Message string `json:"message"`
	// Indicates the invalid field
	Target   *string                 `json:"target,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &ListEntitiesResponseBody{}

func (e *ListEntitiesResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
