// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/solarwinds/swo-sdk-go/swov1/models/components"
)

// UnpauseURIMonitoringResponseBody - The server cannot find the requested resource.
type UnpauseURIMonitoringResponseBody struct {
	// Supporting description of the error
	Message  string                  `json:"message"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &UnpauseURIMonitoringResponseBody{}

func (e *UnpauseURIMonitoringResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
