// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

type CommonConflictErrorResponse struct {
	// Supporting description of the error.
	Message string `json:"message"`
	// Indicates the invalid field.
	Target *string `json:"target,omitempty"`
	// Uniquely identifies an error condition.
	Code     *components.CommonConflictErrorResponseCode `json:"code,omitempty"`
	HTTPMeta components.HTTPMetadata                     `json:"-"`
}

var _ error = &CommonConflictErrorResponse{}

func (e *CommonConflictErrorResponse) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
