// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

type CommonUnavailableErrorResponse struct {
	// Supporting description of the error.
	Message string `json:"message"`
	// Uniquely identifies an error condition.
	Code     *components.CommonUnavailableErrorResponseCode `json:"code,omitempty"`
	HTTPMeta components.HTTPMetadata                        `json:"-"`
}

var _ error = &CommonUnavailableErrorResponse{}

func (e *CommonUnavailableErrorResponse) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
