// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

type CommonInternalErrorResponse struct {
	// Supporting description of the error.
	Message string `json:"message"`
	// Uniquely identifies an error condition.
	Code     *components.CommonInternalErrorResponseCode `json:"code,omitempty"`
	HTTPMeta components.HTTPMetadata                     `json:"-"`
}

var _ error = &CommonInternalErrorResponse{}

func (e *CommonInternalErrorResponse) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
