// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

type CommonUnauthorizedErrorResponse struct {
	// Supporting description of the error.
	Message string `json:"message"`
	// Uniquely identifies an error condition.
	Code     *components.CommonUnauthorizedErrorResponseCode `json:"code,omitempty"`
	HTTPMeta components.HTTPMetadata                         `json:"-"`
}

var _ error = &CommonUnauthorizedErrorResponse{}

func (e *CommonUnauthorizedErrorResponse) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
