// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

// CreateWebsiteBadRequestError - The server could not understand the request due to invalid syntax.
type CreateWebsiteBadRequestError struct {
	// Uniquely identifies an error condition.
	Code *components.CommonDefaultErrorCode `json:"code,omitempty"`
	// Supporting description of the error
	Message string `json:"message"`
	// Indicates the invalid field
	Target   *string                 `json:"target,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &CreateWebsiteBadRequestError{}

func (e *CreateWebsiteBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
