// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

// CreateOrgStructureInternalServerError - Server error
type CreateOrgStructureInternalServerError struct {
	// Uniquely identifies an error condition.
	Code *components.CommonDefaultErrorCode `json:"code,omitempty"`
	// Supporting description of the error
	Message string `json:"message"`
	// Indicates the invalid field
	Target   *string                 `json:"target,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &CreateOrgStructureInternalServerError{}

func (e *CreateOrgStructureInternalServerError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// CreateOrgStructureNotFoundError - The server cannot find the requested resource.
type CreateOrgStructureNotFoundError struct {
	// Uniquely identifies an error condition.
	Code *components.CommonDefaultErrorCode `json:"code,omitempty"`
	// Supporting description of the error
	Message string `json:"message"`
	// Indicates the invalid field
	Target   *string                 `json:"target,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &CreateOrgStructureNotFoundError{}

func (e *CreateOrgStructureNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// CreateOrgStructureUnauthorizedError - Access is unauthorized.
type CreateOrgStructureUnauthorizedError struct {
	// Uniquely identifies an error condition.
	Code *components.CommonDefaultErrorCode `json:"code,omitempty"`
	// Supporting description of the error
	Message string `json:"message"`
	// Indicates the invalid field
	Target   *string                 `json:"target,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &CreateOrgStructureUnauthorizedError{}

func (e *CreateOrgStructureUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// CreateOrgStructureBadRequestError - The server could not understand the request due to invalid syntax.
type CreateOrgStructureBadRequestError struct {
	// Uniquely identifies an error condition.
	Code *components.CommonDefaultErrorCode `json:"code,omitempty"`
	// Supporting description of the error
	Message string `json:"message"`
	// Indicates the invalid field
	Target   *string                 `json:"target,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &CreateOrgStructureBadRequestError{}

func (e *CreateOrgStructureBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
