// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

// DeleteCompositeMetricNotFoundError - The server cannot find the requested resource.
type DeleteCompositeMetricNotFoundError struct {
	// Uniquely identifies an error condition.
	Code *components.CommonDefaultErrorCode `json:"code,omitempty"`
	// Supporting description of the error
	Message string `json:"message"`
	// Indicates the invalid field
	Target   *string                 `json:"target,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &DeleteCompositeMetricNotFoundError{}

func (e *DeleteCompositeMetricNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// DeleteCompositeMetricForbiddenError - Access is forbidden.
type DeleteCompositeMetricForbiddenError struct {
	// Uniquely identifies an error condition.
	Code *components.MetricErrorCode `json:"code,omitempty"`
	// Supporting description of the error
	Message string `json:"message"`
	// Indicates the invalid field
	Target   *string                 `json:"target,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &DeleteCompositeMetricForbiddenError{}

func (e *DeleteCompositeMetricForbiddenError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
