// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

// DeleteDatabaseNotFoundError - The server cannot find the requested resource.
type DeleteDatabaseNotFoundError struct {
	// Uniquely identifies an error condition.
	Code *components.CommonDefaultErrorCode `json:"code,omitempty"`
	// Supporting description of the error
	Message string `json:"message"`
	// Indicates the invalid field
	Target   *string                 `json:"target,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &DeleteDatabaseNotFoundError{}

func (e *DeleteDatabaseNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// DeleteDatabaseBadRequestError - The server could not understand the request due to invalid syntax.
type DeleteDatabaseBadRequestError struct {
	// Uniquely identifies an error condition.
	Code *components.CommonDefaultErrorCode `json:"code,omitempty"`
	// Supporting description of the error
	Message string `json:"message"`
	// Indicates the invalid field
	Target   *string                 `json:"target,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &DeleteDatabaseBadRequestError{}

func (e *DeleteDatabaseBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
