// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

// GetPublicKeyDboResponseBody - The server cannot find the requested resource.
type GetPublicKeyDboResponseBody struct {
	// Supporting description of the error
	Message  string                  `json:"message"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &GetPublicKeyDboResponseBody{}

func (e *GetPublicKeyDboResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetPublicKeyResponseBody - The server could not understand the request due to invalid syntax.
type GetPublicKeyResponseBody struct {
	// Supporting description of the error
	Message string `json:"message"`
	// Indicates the invalid field
	Target   *string                 `json:"target,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &GetPublicKeyResponseBody{}

func (e *GetPublicKeyResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
