// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

// GetPluginsNotFoundError - The server cannot find the requested resource.
type GetPluginsNotFoundError struct {
	// Uniquely identifies an error condition.
	Code *components.CommonDefaultErrorCode `json:"code,omitempty"`
	// Supporting description of the error
	Message string `json:"message"`
	// Indicates the invalid field
	Target   *string                 `json:"target,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &GetPluginsNotFoundError{}

func (e *GetPluginsNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetPluginsBadRequestError - The server could not understand the request due to invalid syntax.
type GetPluginsBadRequestError struct {
	// Uniquely identifies an error condition.
	Code *components.CommonDefaultErrorCode `json:"code,omitempty"`
	// Supporting description of the error
	Message string `json:"message"`
	// Indicates the invalid field
	Target   *string                 `json:"target,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &GetPluginsBadRequestError{}

func (e *GetPluginsBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
