// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

// GetPublicKeyNotFoundError - The server cannot find the requested resource.
type GetPublicKeyNotFoundError struct {
	// Uniquely identifies an error condition.
	Code *components.CommonDefaultErrorCode `json:"code,omitempty"`
	// Supporting description of the error
	Message string `json:"message"`
	// Indicates the invalid field
	Target   *string                 `json:"target,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &GetPublicKeyNotFoundError{}

func (e *GetPublicKeyNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetPublicKeyBadRequestError - The server could not understand the request due to invalid syntax.
type GetPublicKeyBadRequestError struct {
	// Uniquely identifies an error condition.
	Code *components.CommonDefaultErrorCode `json:"code,omitempty"`
	// Supporting description of the error
	Message string `json:"message"`
	// Indicates the invalid field
	Target   *string                 `json:"target,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &GetPublicKeyBadRequestError{}

func (e *GetPublicKeyBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
