// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

// ListMultiMetricMeasurementsResponseBody - The server could not understand the request due to invalid syntax.
type ListMultiMetricMeasurementsResponseBody struct {
	// HTTP status code as defined in RFC 2817
	Code int64 `json:"code"`
	// Supporting description of the error
	Message  string                  `json:"message"`
	Target   *string                 `json:"target,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &ListMultiMetricMeasurementsResponseBody{}

func (e *ListMultiMetricMeasurementsResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
