// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

// ListMultiMetricMeasurementsBadRequestError - The server could not understand the request due to invalid syntax.
type ListMultiMetricMeasurementsBadRequestError struct {
	// Uniquely identifies an error condition.
	Code *components.CommonDefaultErrorCode `json:"code,omitempty"`
	// Supporting description of the error
	Message string `json:"message"`
	// Indicates the invalid field
	Target   *string                 `json:"target,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &ListMultiMetricMeasurementsBadRequestError{}

func (e *ListMultiMetricMeasurementsBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
