// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

// ObserveDatabaseResponseBody - The server could not understand the request due to invalid syntax.
type ObserveDatabaseResponseBody struct {
	// Supporting description of the error
	Message string `json:"message"`
	// Indicates the invalid field
	Target   *string                 `json:"target,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &ObserveDatabaseResponseBody{}

func (e *ObserveDatabaseResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
