// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

// PluginOperationNotFoundError - The server cannot find the requested resource.
type PluginOperationNotFoundError struct {
	// Uniquely identifies an error condition.
	Code *components.CommonDefaultErrorCode `json:"code,omitempty"`
	// Supporting description of the error
	Message string `json:"message"`
	// Indicates the invalid field
	Target   *string                 `json:"target,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &PluginOperationNotFoundError{}

func (e *PluginOperationNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// PluginOperationBadRequestError - The server could not understand the request due to invalid syntax.
type PluginOperationBadRequestError struct {
	// Uniquely identifies an error condition.
	Code *components.CommonDefaultErrorCode `json:"code,omitempty"`
	// Supporting description of the error
	Message string `json:"message"`
	// Indicates the invalid field
	Target   *string                 `json:"target,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &PluginOperationBadRequestError{}

func (e *PluginOperationBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
