// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

// UpdateCompositeMetricMetricsResponseResponseBody - The server cannot find the requested resource.
type UpdateCompositeMetricMetricsResponseResponseBody struct {
	// Supporting description of the error
	Message  string                  `json:"message"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &UpdateCompositeMetricMetricsResponseResponseBody{}

func (e *UpdateCompositeMetricMetricsResponseResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UpdateCompositeMetricMetricsResponseBody - Access is forbidden.
type UpdateCompositeMetricMetricsResponseBody struct {
	// Supporting description of the error
	Message  string                  `json:"message"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &UpdateCompositeMetricMetricsResponseBody{}

func (e *UpdateCompositeMetricMetricsResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UpdateCompositeMetricResponseBody - The server could not understand the request due to invalid syntax.
type UpdateCompositeMetricResponseBody struct {
	// Supporting description of the error
	Message string `json:"message"`
	// Indicates the invalid field
	Target   *string                 `json:"target,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &UpdateCompositeMetricResponseBody{}

func (e *UpdateCompositeMetricResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
