// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

// UpdateEntityByIDNotFoundError - The server cannot find the requested resource.
type UpdateEntityByIDNotFoundError struct {
	// Uniquely identifies an error condition.
	Code *components.CommonDefaultErrorCode `json:"code,omitempty"`
	// Supporting description of the error
	Message string `json:"message"`
	// Indicates the invalid field
	Target   *string                 `json:"target,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &UpdateEntityByIDNotFoundError{}

func (e *UpdateEntityByIDNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UpdateEntityByIDUnauthorizedError - Access is unauthorized.
type UpdateEntityByIDUnauthorizedError struct {
	// Uniquely identifies an error condition.
	Code *components.CommonDefaultErrorCode `json:"code,omitempty"`
	// Supporting description of the error
	Message string `json:"message"`
	// Indicates the invalid field
	Target   *string                 `json:"target,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &UpdateEntityByIDUnauthorizedError{}

func (e *UpdateEntityByIDUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UpdateEntityByIDBadRequestError - The server could not understand the request due to invalid syntax.
type UpdateEntityByIDBadRequestError struct {
	// Uniquely identifies an error condition.
	Code *components.CommonDefaultErrorCode `json:"code,omitempty"`
	// Supporting description of the error
	Message string `json:"message"`
	// Indicates the invalid field
	Target   *string                 `json:"target,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &UpdateEntityByIDBadRequestError{}

func (e *UpdateEntityByIDBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
