// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

// ValidateMgmtAccountOnboardingCloudAccountsResponseResponseBody - Server error
type ValidateMgmtAccountOnboardingCloudAccountsResponseResponseBody struct {
	// Supporting description of the error
	Message  string                  `json:"message"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &ValidateMgmtAccountOnboardingCloudAccountsResponseResponseBody{}

func (e *ValidateMgmtAccountOnboardingCloudAccountsResponseResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// ValidateMgmtAccountOnboardingCloudAccountsResponseBody - Access is unauthorized.
type ValidateMgmtAccountOnboardingCloudAccountsResponseBody struct {
	// Supporting description of the error
	Message  string                  `json:"message"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &ValidateMgmtAccountOnboardingCloudAccountsResponseBody{}

func (e *ValidateMgmtAccountOnboardingCloudAccountsResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// ValidateMgmtAccountOnboardingResponseBody - The server could not understand the request due to invalid syntax.
type ValidateMgmtAccountOnboardingResponseBody struct {
	// Supporting description of the error
	Message string `json:"message"`
	// Indicates the invalid field
	Target   *string                 `json:"target,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &ValidateMgmtAccountOnboardingResponseBody{}

func (e *ValidateMgmtAccountOnboardingResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
