// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package handler

import (
	"fmt"
	"log"
	"mockserver/internal/handler/assert"
	"mockserver/internal/logging"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/types"
	"mockserver/internal/sdk/utils"
	"mockserver/internal/tracking"
	"net/http"
)

func pathGetV1MetricsName(dir *logging.HTTPFileDirectory, rt *tracking.RequestTracker) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		test := req.Header.Get("x-speakeasy-test-name")
		instanceID := req.Header.Get("x-speakeasy-test-instance-id")

		count := rt.GetRequestCount(test, instanceID)

		switch fmt.Sprintf("%s[%d]", test, count) {
		case "composite-metrics-crud-lifecycle[1]":
			dir.HandlerFunc("getMetricByName", testGetMetricByNameCompositeMetricsCrudLifecycle1)(w, req)
		case "composite-metrics-crud-lifecycle[3]":
			dir.HandlerFunc("getMetricByName", testGetMetricByNameCompositeMetricsCrudLifecycle3)(w, req)
		default:
			http.Error(w, fmt.Sprintf("Unknown test: %s[%d]", test, count), http.StatusBadRequest)
		}
	}
}

func testGetMetricByNameCompositeMetricsCrudLifecycle1(w http.ResponseWriter, req *http.Request) {
	if err := assert.SecurityAuthorizationHeader(req, false, "Bearer"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusUnauthorized)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *components.CommonMetricInfo = &components.CommonMetricInfo{
		Name:             "composite.swo.sdk.e2e.create.metric.test",
		DisplayName:      types.String("SWO SDK E2E Create Metric Test"),
		Description:      types.String("SWO SDK composite metric end to end create test"),
		Units:            types.String("bytes/s"),
		Formula:          types.String("rate(system.disk.io[1m])"),
		LastReportedTime: types.MustNewTimeFromString("2024-11-25T16:38:24Z"),
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(respBodyBytes)
}

func testGetMetricByNameCompositeMetricsCrudLifecycle3(w http.ResponseWriter, req *http.Request) {
	if err := assert.SecurityAuthorizationHeader(req, false, "Bearer"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusUnauthorized)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *components.CommonMetricInfo = &components.CommonMetricInfo{
		Name:             "composite.swo.sdk.e2e.create.metric.test",
		DisplayName:      types.String("SWO SDK E2E Updated Metric Test"),
		Description:      types.String("SWO SDK composite metric end to end updated test"),
		Units:            types.String("bytes/s"),
		Formula:          types.String("rate(system.cpu.usage[2m])"),
		LastReportedTime: types.MustNewTimeFromString("2024-11-25T16:38:24Z"),
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(respBodyBytes)
}
