workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    swov1:
        inputs:
            - location: https://api.na-01.cloud.solarwinds.com/v1/openapi.json
        overlays:
            - location: swov1/.speakeasy/overlays/auth.yaml
        registry:
            location: registry.speakeasyapi.dev/swo/swo/solar-winds-observability
targets:
    swov1:
        target: go
        source: swov1
        output: swov1
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/swo/swo/solar-winds-observability-go-code-samples
            labelOverride:
                fixedValue: Go (SDK)
            blocking: false
