// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/solarwinds/swo-sdk-go/solarwinds/models/components"
)

type Details struct {
	Error string `json:"error"`
}

func (o *Details) GetError() string {
	if o == nil {
		return ""
	}
	return o.Error
}

type InnerError struct {
	Code       string `json:"code"`
	InnerError string `json:"innerError"`
}

func (o *InnerError) GetCode() string {
	if o == nil {
		return ""
	}
	return o.Code
}

func (o *InnerError) GetInnerError() string {
	if o == nil {
		return ""
	}
	return o.InnerError
}

// CreateWebsiteMonitorResponseBody - The server could not understand the request due to invalid syntax.
type CreateWebsiteMonitorResponseBody struct {
	Code       string                  `json:"code"`
	Message    string                  `json:"message"`
	Target     *string                 `json:"target,omitempty"`
	Details    []Details               `json:"details,omitempty"`
	InnerError *InnerError             `json:"innerError,omitempty"`
	HTTPMeta   components.HTTPMetadata `json:"-"`
}

var _ error = &CreateWebsiteMonitorResponseBody{}

func (e *CreateWebsiteMonitorResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
