// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type CreateCompositeMetricResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded and a new resource has been created as a result.
	MetricsCompositeMetric *components.MetricsCompositeMetric
}

func (o *CreateCompositeMetricResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateCompositeMetricResponse) GetMetricsCompositeMetric() *components.MetricsCompositeMetric {
	if o == nil {
		return nil
	}
	return o.MetricsCompositeMetric
}
