// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type DeleteDatabaseRequest struct {
	EntityID string `pathParam:"style=simple,explode=false,name=entityId"`
}

func (o *DeleteDatabaseRequest) GetEntityID() string {
	if o == nil {
		return ""
	}
	return o.EntityID
}

type DeleteDatabaseResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *DeleteDatabaseResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
