// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type DeleteIntegrationRequest struct {
	// Integration type, e.g. nginx or mysql.
	Type string `pathParam:"style=simple,explode=false,name=type"`
	// SWO Agent client ID.
	ClientID string `pathParam:"style=simple,explode=false,name=clientId"`
	// Integration ID (stable public identifier sourced from the relevant pluginInstanceId).
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Entity IDs to delete alongside the integration. Must be values from the integration's entityIds field. Omit to skip entity deletion.
	EntityIds []string `queryParam:"style=form,explode=true,name=entityIds"`
}

func (o *DeleteIntegrationRequest) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

func (o *DeleteIntegrationRequest) GetClientID() string {
	if o == nil {
		return ""
	}
	return o.ClientID
}

func (o *DeleteIntegrationRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *DeleteIntegrationRequest) GetEntityIds() []string {
	if o == nil {
		return nil
	}
	return o.EntityIds
}

type DeleteIntegrationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *DeleteIntegrationResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
