// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetDemSettingsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	DemOutageConfiguration *components.DemOutageConfiguration
}

func (o *GetDemSettingsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetDemSettingsResponse) GetDemOutageConfiguration() *components.DemOutageConfiguration {
	if o == nil {
		return nil
	}
	return o.DemOutageConfiguration
}
