// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
	"time"
)

type GetURIOutageStatusesRequest struct {
	EntityID string `pathParam:"style=simple,explode=false,name=entityId"`
	// Start of timespan to get results for, inclusive
	StartTime time.Time `queryParam:"style=form,explode=false,name=startTime"`
	// End of timespan to get results for, exclusive
	EndTime time.Time `queryParam:"style=form,explode=false,name=endTime"`
	// sort direction: 'backward' and 'tail' both sort from oldest to newest, 'forward' sorts from newest to oldest
	Direction *components.DemSortDirectionParam `default:"backward" queryParam:"style=form,explode=false,name=direction"`
	// Number of items in a response page. Default varies by API.
	PageSize *int `queryParam:"style=form,explode=false,name=pageSize"`
	// Token for the requested page.
	SkipToken *string `queryParam:"style=form,explode=false,name=skipToken"`
}

func (g GetURIOutageStatusesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetURIOutageStatusesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"entityId", "startTime", "endTime"}); err != nil {
		return err
	}
	return nil
}

func (o *GetURIOutageStatusesRequest) GetEntityID() string {
	if o == nil {
		return ""
	}
	return o.EntityID
}

func (o *GetURIOutageStatusesRequest) GetStartTime() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.StartTime
}

func (o *GetURIOutageStatusesRequest) GetEndTime() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.EndTime
}

func (o *GetURIOutageStatusesRequest) GetDirection() *components.DemSortDirectionParam {
	if o == nil {
		return nil
	}
	return o.Direction
}

func (o *GetURIOutageStatusesRequest) GetPageSize() *int {
	if o == nil {
		return nil
	}
	return o.PageSize
}

func (o *GetURIOutageStatusesRequest) GetSkipToken() *string {
	if o == nil {
		return nil
	}
	return o.SkipToken
}

// GetURIOutageStatusesResponseBody - An array of outage statuses with pagination info
type GetURIOutageStatusesResponseBody struct {
	// Uri outage statuses
	Statuses []components.DemOutageStatus `json:"statuses"`
	// Pagination information
	PageInfo components.CommonPageInfo `json:"pageInfo"`
}

func (o *GetURIOutageStatusesResponseBody) GetStatuses() []components.DemOutageStatus {
	if o == nil {
		return []components.DemOutageStatus{}
	}
	return o.Statuses
}

func (o *GetURIOutageStatusesResponseBody) GetPageInfo() components.CommonPageInfo {
	if o == nil {
		return components.CommonPageInfo{}
	}
	return o.PageInfo
}

type GetURIOutageStatusesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// An array of outage statuses with pagination info
	Object *GetURIOutageStatusesResponseBody

	Next func() (*GetURIOutageStatusesResponse, error)
}

func (o *GetURIOutageStatusesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetURIOutageStatusesResponse) GetObject() *GetURIOutageStatusesResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
