// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
	"time"
)

type GetWebsiteTestResultsRequest struct {
	EntityID string `pathParam:"style=simple,explode=false,name=entityId"`
	// Start of timespan to get results for, inclusive
	StartTime time.Time `queryParam:"style=form,explode=false,name=startTime"`
	// End of timespan to get results for, exclusive
	EndTime time.Time `queryParam:"style=form,explode=false,name=endTime"`
	// sort direction: 'backward' and 'tail' both sort from oldest to newest, 'forward' sorts from newest to oldest
	Direction *components.DemSortDirectionParam `default:"backward" queryParam:"style=form,explode=false,name=direction"`
	// Minimal result response time to return, inclusive, defaults to -1
	MinResponse *int `queryParam:"style=form,explode=false,name=minResponse"`
	// Maximal result response time to return, exclusive, defaults to infinity
	MaxResponse *int `queryParam:"style=form,explode=false,name=maxResponse"`
	// Ids of probes to return results from (comma-separated list). Defaults to all probes.
	Probes *string `queryParam:"style=form,explode=false,name=probes"`
	// Test result statuses to include. Defaults to all statuses
	Status *components.DemTestResultsParamsStatus `queryParam:"style=form,explode=false,name=status"`
	// Number of items in a response page. Default varies by API.
	PageSize *int `queryParam:"style=form,explode=false,name=pageSize"`
	// Token for the requested page.
	SkipToken *string `queryParam:"style=form,explode=false,name=skipToken"`
}

func (g GetWebsiteTestResultsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetWebsiteTestResultsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"entityId", "startTime", "endTime"}); err != nil {
		return err
	}
	return nil
}

func (o *GetWebsiteTestResultsRequest) GetEntityID() string {
	if o == nil {
		return ""
	}
	return o.EntityID
}

func (o *GetWebsiteTestResultsRequest) GetStartTime() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.StartTime
}

func (o *GetWebsiteTestResultsRequest) GetEndTime() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.EndTime
}

func (o *GetWebsiteTestResultsRequest) GetDirection() *components.DemSortDirectionParam {
	if o == nil {
		return nil
	}
	return o.Direction
}

func (o *GetWebsiteTestResultsRequest) GetMinResponse() *int {
	if o == nil {
		return nil
	}
	return o.MinResponse
}

func (o *GetWebsiteTestResultsRequest) GetMaxResponse() *int {
	if o == nil {
		return nil
	}
	return o.MaxResponse
}

func (o *GetWebsiteTestResultsRequest) GetProbes() *string {
	if o == nil {
		return nil
	}
	return o.Probes
}

func (o *GetWebsiteTestResultsRequest) GetStatus() *components.DemTestResultsParamsStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *GetWebsiteTestResultsRequest) GetPageSize() *int {
	if o == nil {
		return nil
	}
	return o.PageSize
}

func (o *GetWebsiteTestResultsRequest) GetSkipToken() *string {
	if o == nil {
		return nil
	}
	return o.SkipToken
}

// GetWebsiteTestResultsResponseBody - An array of test results with pagination info
type GetWebsiteTestResultsResponseBody struct {
	// Website test results
	Results []components.DemTestResult `json:"results"`
	// Pagination information
	PageInfo components.CommonPageInfo `json:"pageInfo"`
}

func (o *GetWebsiteTestResultsResponseBody) GetResults() []components.DemTestResult {
	if o == nil {
		return []components.DemTestResult{}
	}
	return o.Results
}

func (o *GetWebsiteTestResultsResponseBody) GetPageInfo() components.CommonPageInfo {
	if o == nil {
		return components.CommonPageInfo{}
	}
	return o.PageInfo
}

type GetWebsiteTestResultsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// An array of test results with pagination info
	Object *GetWebsiteTestResultsResponseBody

	Next func() (*GetWebsiteTestResultsResponse, error)
}

func (o *GetWebsiteTestResultsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetWebsiteTestResultsResponse) GetObject() *GetWebsiteTestResultsResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
