// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type ListProbesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	DemListProbesResponse *components.DemListProbesResponse
}

func (o *ListProbesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListProbesResponse) GetDemListProbesResponse() *components.DemListProbesResponse {
	if o == nil {
		return nil
	}
	return o.DemListProbesResponse
}
