// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type ListIntegrationsRequest struct {
	// Number of items in a response page. Default varies by API.
	PageSize *int `queryParam:"style=form,explode=false,name=pageSize"`
	// Token for the requested page.
	SkipToken *string `queryParam:"style=form,explode=false,name=skipToken"`
}

func (o *ListIntegrationsRequest) GetPageSize() *int {
	if o == nil {
		return nil
	}
	return o.PageSize
}

func (o *ListIntegrationsRequest) GetSkipToken() *string {
	if o == nil {
		return nil
	}
	return o.SkipToken
}

// ListIntegrationsResponseBody - The request has succeeded.
type ListIntegrationsResponseBody struct {
	// Integration instances.
	Items []components.IntegrationsIntegration `json:"items"`
	// Pagination information.
	PageInfo components.CommonPageInfo `json:"pageInfo"`
}

func (o *ListIntegrationsResponseBody) GetItems() []components.IntegrationsIntegration {
	if o == nil {
		return []components.IntegrationsIntegration{}
	}
	return o.Items
}

func (o *ListIntegrationsResponseBody) GetPageInfo() components.CommonPageInfo {
	if o == nil {
		return components.CommonPageInfo{}
	}
	return o.PageInfo
}

type ListIntegrationsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *ListIntegrationsResponseBody

	Next func() (*ListIntegrationsResponse, error)
}

func (o *ListIntegrationsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListIntegrationsResponse) GetObject() *ListIntegrationsResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
