// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type PauseURIMonitoringRequest struct {
	EntityID string `pathParam:"style=simple,explode=false,name=entityId"`
}

func (o *PauseURIMonitoringRequest) GetEntityID() string {
	if o == nil {
		return ""
	}
	return o.EntityID
}

type PauseURIMonitoringResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	EntityID *components.EntityID
}

func (o *PauseURIMonitoringResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PauseURIMonitoringResponse) GetEntityID() *components.EntityID {
	if o == nil {
		return nil
	}
	return o.EntityID
}
