// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type PluginOperationRequest struct {
	// Entity ID.
	EntityID string `pathParam:"style=simple,explode=false,name=entityId"`
	// Name of the operation to apply to the plugin.
	Operation string `pathParam:"style=simple,explode=false,name=operation"`
}

func (o *PluginOperationRequest) GetEntityID() string {
	if o == nil {
		return ""
	}
	return o.EntityID
}

func (o *PluginOperationRequest) GetOperation() string {
	if o == nil {
		return ""
	}
	return o.Operation
}

type PluginOperationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *PluginOperationResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
