// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type UpdateTransactionRequest struct {
	EntityID string `pathParam:"style=simple,explode=false,name=entityId"`
	// Update transaction monitoring configuration
	Body components.DemTransaction `request:"mediaType=application/json"`
}

func (o *UpdateTransactionRequest) GetEntityID() string {
	if o == nil {
		return ""
	}
	return o.EntityID
}

func (o *UpdateTransactionRequest) GetBody() components.DemTransaction {
	if o == nil {
		return components.DemTransaction{}
	}
	return o.Body
}

type UpdateTransactionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	CommonEntityID *components.CommonEntityID
}

func (o *UpdateTransactionResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateTransactionResponse) GetCommonEntityID() *components.CommonEntityID {
	if o == nil {
		return nil
	}
	return o.CommonEntityID
}
