// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type UpdateWebsiteRequest struct {
	EntityID string `pathParam:"style=simple,explode=false,name=entityId"`
	// The updated website monitoring configuration
	Body components.DemWebsite `request:"mediaType=application/json"`
}

func (o *UpdateWebsiteRequest) GetEntityID() string {
	if o == nil {
		return ""
	}
	return o.EntityID
}

func (o *UpdateWebsiteRequest) GetBody() components.DemWebsite {
	if o == nil {
		return components.DemWebsite{}
	}
	return o.Body
}

type UpdateWebsiteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	CommonEntityID *components.CommonEntityID
}

func (o *UpdateWebsiteResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateWebsiteResponse) GetCommonEntityID() *components.CommonEntityID {
	if o == nil {
		return nil
	}
	return o.CommonEntityID
}
