// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type UpdateAwsIntegrationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	UpdateAwsIntegrationResponse *components.UpdateAwsIntegrationResponse
}

func (o *UpdateAwsIntegrationResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateAwsIntegrationResponse) GetUpdateAwsIntegrationResponse() *components.UpdateAwsIntegrationResponse {
	if o == nil {
		return nil
	}
	return o.UpdateAwsIntegrationResponse
}
