// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type UpdateURIRequest struct {
	EntityID string `pathParam:"style=simple,explode=false,name=entityId"`
	// The updated URI monitoring configuration
	Body components.DemURI `request:"mediaType=application/json"`
}

func (o *UpdateURIRequest) GetEntityID() string {
	if o == nil {
		return ""
	}
	return o.EntityID
}

func (o *UpdateURIRequest) GetBody() components.DemURI {
	if o == nil {
		return components.DemURI{}
	}
	return o.Body
}

type UpdateURIResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	CommonEntityID *components.CommonEntityID
}

func (o *UpdateURIResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateURIResponse) GetCommonEntityID() *components.CommonEntityID {
	if o == nil {
		return nil
	}
	return o.CommonEntityID
}
