// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CloudAccountsAwsMgmtAccountOnboardingResponse struct {
	// True if the Management Account is onboarded, false otherwise.
	IsOnboarded bool `json:"isOnboarded"`
}

func (o *CloudAccountsAwsMgmtAccountOnboardingResponse) GetIsOnboarded() bool {
	if o == nil {
		return false
	}
	return o.IsOnboarded
}
