// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CloudAccountsAwsMgmtAccountOnboardingRequest struct {
	// AWS Control Tower Management Account ID.
	ManagementAccountID string `queryParam:"name=managementAccountId"`
}

func (o *CloudAccountsAwsMgmtAccountOnboardingRequest) GetManagementAccountID() string {
	if o == nil {
		return ""
	}
	return o.ManagementAccountID
}
