// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DatabasePluginConfig struct {
	// Name of plugin observing database server
	PluginName string `json:"pluginName"`
	// Configuration of plugin observing database server
	Config []CommonKeyValuePair `json:"config"`
}

func (o *DatabasePluginConfig) GetPluginName() string {
	if o == nil {
		return ""
	}
	return o.PluginName
}

func (o *DatabasePluginConfig) GetConfig() []CommonKeyValuePair {
	if o == nil {
		return []CommonKeyValuePair{}
	}
	return o.Config
}
