// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DboDatabasePluginStatusResponse struct {
	// Status of plugin(s) observing database server
	Plugins []DboDatabasePluginStatus `json:"plugins"`
}

func (o *DboDatabasePluginStatusResponse) GetPlugins() []DboDatabasePluginStatus {
	if o == nil {
		return []DboDatabasePluginStatus{}
	}
	return o.Plugins
}
