// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/solarwinds/swo-sdk-go/swov1/internal/utils"
)

type DboUpdateDatabaseRequest struct {
	// Name for the observed database entity
	Name *string `default:"" json:"name"`
	// Optional advanced configuration options for plugins, e.g. disable-sampling set to true
	ConfigOptions []CommonKeyValuePair `json:"configOptions,omitempty"`
	// Options specifying how plugins connect to database server, authentication method change is not supported
	DbConnOptions *DboDatabaseConnectionOptionsUpdate `json:"dbConnOptions,omitempty"`
	// Tags for observed database entity
	Tags []CommonKeyValuePair `json:"tags,omitempty"`
	// Host entity/entities where database server is deployed on
	DeployedOn []string `json:"deployedOn,omitempty"`
}

func (d DboUpdateDatabaseRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DboUpdateDatabaseRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DboUpdateDatabaseRequest) GetName() *string {
	if d == nil {
		return nil
	}
	return d.Name
}

func (d *DboUpdateDatabaseRequest) GetConfigOptions() []CommonKeyValuePair {
	if d == nil {
		return nil
	}
	return d.ConfigOptions
}

func (d *DboUpdateDatabaseRequest) GetDbConnOptions() *DboDatabaseConnectionOptionsUpdate {
	if d == nil {
		return nil
	}
	return d.DbConnOptions
}

func (d *DboUpdateDatabaseRequest) GetTags() []CommonKeyValuePair {
	if d == nil {
		return nil
	}
	return d.Tags
}

func (d *DboUpdateDatabaseRequest) GetDeployedOn() []string {
	if d == nil {
		return nil
	}
	return d.DeployedOn
}
