// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/solarwinds/swo-sdk-go/swov1/internal/utils"
	"time"
)

type DemGetWebsiteResponseStatus string

const (
	DemGetWebsiteResponseStatusUp          DemGetWebsiteResponseStatus = "up"
	DemGetWebsiteResponseStatusDown        DemGetWebsiteResponseStatus = "down"
	DemGetWebsiteResponseStatusPaused      DemGetWebsiteResponseStatus = "paused"
	DemGetWebsiteResponseStatusMaintenance DemGetWebsiteResponseStatus = "maintenance"
	DemGetWebsiteResponseStatusUnknown     DemGetWebsiteResponseStatus = "unknown"
)

func (e DemGetWebsiteResponseStatus) ToPointer() *DemGetWebsiteResponseStatus {
	return &e
}
func (e *DemGetWebsiteResponseStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "up":
		fallthrough
	case "down":
		fallthrough
	case "paused":
		fallthrough
	case "maintenance":
		fallthrough
	case "unknown":
		*e = DemGetWebsiteResponseStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DemGetWebsiteResponseStatus: %v", v)
	}
}

// MonitoringOptions - Defines which monitoring features are enabled for a website.
type MonitoringOptions struct {
	// True if the availability monitoring is active.
	IsAvailabilityActive bool `json:"isAvailabilityActive"`
	// True if the real user monitoring (RUM) is active.
	IsRumActive bool `json:"isRumActive"`
}

func (o *MonitoringOptions) GetIsAvailabilityActive() bool {
	if o == nil {
		return false
	}
	return o.IsAvailabilityActive
}

func (o *MonitoringOptions) GetIsRumActive() bool {
	if o == nil {
		return false
	}
	return o.IsRumActive
}

// DemGetWebsiteResponsePlatformOptions - Configure cloud platforms of the synthetic availability test probes. If omitted or set to null, no particular cloud platform will be enforced.
type DemGetWebsiteResponsePlatformOptions struct {
	// Cloud platforms hosting synthetic probes.
	ProbePlatforms []DemProbePlatform `json:"probePlatforms"`
	//   Use this field to configure whether availability tests should be performed from all selected
	//   platforms or one randomly selected platform. It has no effect if you provided only one platform
	//   in the `probePlatforms` field.
	//
	//   If set to true, a separate test is made from each of the selected platforms.
	//
	//   If set to false, only one of the selected platforms is chosen every time.
	//
	//   If omitted, the previous setting will stay in effect. If there is no previous setting, the value
	//   will default to false.
	TestFromAll *bool `json:"testFromAll,omitempty"`
}

func (o *DemGetWebsiteResponsePlatformOptions) GetProbePlatforms() []DemProbePlatform {
	if o == nil {
		return []DemProbePlatform{}
	}
	return o.ProbePlatforms
}

func (o *DemGetWebsiteResponsePlatformOptions) GetTestFromAll() *bool {
	if o == nil {
		return nil
	}
	return o.TestFromAll
}

// DemGetWebsiteResponseFailingTestLocations - How many locations must report a failure for an entity to be considered down.
type DemGetWebsiteResponseFailingTestLocations string

const (
	DemGetWebsiteResponseFailingTestLocationsAll DemGetWebsiteResponseFailingTestLocations = "all"
	DemGetWebsiteResponseFailingTestLocationsAny DemGetWebsiteResponseFailingTestLocations = "any"
)

func (e DemGetWebsiteResponseFailingTestLocations) ToPointer() *DemGetWebsiteResponseFailingTestLocations {
	return &e
}
func (e *DemGetWebsiteResponseFailingTestLocations) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "all":
		fallthrough
	case "any":
		*e = DemGetWebsiteResponseFailingTestLocations(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DemGetWebsiteResponseFailingTestLocations: %v", v)
	}
}

// DemGetWebsiteResponseOutageConfiguration -   Default conditions when the entity is considered down.
//
//	If omitted or set to null, organization configuration will be used for this entity.
type DemGetWebsiteResponseOutageConfiguration struct {
	// How many locations must report a failure for an entity to be considered down.
	FailingTestLocations DemGetWebsiteResponseFailingTestLocations `json:"failingTestLocations"`
	// Number of consecutive failing tests for an entity to be considered down.
	ConsecutiveForDown int `json:"consecutiveForDown"`
}

func (o *DemGetWebsiteResponseOutageConfiguration) GetFailingTestLocations() DemGetWebsiteResponseFailingTestLocations {
	if o == nil {
		return DemGetWebsiteResponseFailingTestLocations("")
	}
	return o.FailingTestLocations
}

func (o *DemGetWebsiteResponseOutageConfiguration) GetConsecutiveForDown() int {
	if o == nil {
		return 0
	}
	return o.ConsecutiveForDown
}

// DemGetWebsiteResponseOperator - Defines whether the check should pass only when the string is present on the page (CONTAINS) or only when it is absent (DOES_NOT_CONTAIN).
type DemGetWebsiteResponseOperator string

const (
	DemGetWebsiteResponseOperatorContains       DemGetWebsiteResponseOperator = "CONTAINS"
	DemGetWebsiteResponseOperatorDoesNotContain DemGetWebsiteResponseOperator = "DOES_NOT_CONTAIN"
)

func (e DemGetWebsiteResponseOperator) ToPointer() *DemGetWebsiteResponseOperator {
	return &e
}
func (e *DemGetWebsiteResponseOperator) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "CONTAINS":
		fallthrough
	case "DOES_NOT_CONTAIN":
		*e = DemGetWebsiteResponseOperator(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DemGetWebsiteResponseOperator: %v", v)
	}
}

// DemGetWebsiteResponseCheckForString -   Use this field to configure whether availability tests should check for presence or absence of a particular string on a page.
//
//	If the operator is DOES_NOT_CONTAIN and the value is found on the page, the availability test will fail.
//	Likewise, if the operator is CONTAINS and the value is not found on the page, the availability test will fail.
//	If omitted or set to null, the string checking functionality will be disabled.
type DemGetWebsiteResponseCheckForString struct {
	// Defines whether the check should pass only when the string is present on the page (CONTAINS) or only when it is absent (DOES_NOT_CONTAIN).
	Operator DemGetWebsiteResponseOperator `json:"operator"`
	// The string that which will be searched in the page source code.
	Value string `json:"value"`
}

func (o *DemGetWebsiteResponseCheckForString) GetOperator() DemGetWebsiteResponseOperator {
	if o == nil {
		return DemGetWebsiteResponseOperator("")
	}
	return o.Operator
}

func (o *DemGetWebsiteResponseCheckForString) GetValue() string {
	if o == nil {
		return ""
	}
	return o.Value
}

// DemGetWebsiteResponseSsl -   Configure monitoring of SSL/TLS certificates validity. This option is relevant for HTTPS protocol only.
//
//	If omitted or set to null, SSL monitoring will be disabled and its previous configuration discarded.
type DemGetWebsiteResponseSsl struct {
	//   Whether SSL monitoring is enabled for the website.
	//   If set to false, SSL monitoring will be disabled, but the other settings will be remembered in case you re-enable it later.
	//   If omitted, the previous setting will stay in effect. If there is no previous setting, the value will default to false.
	Enabled *bool `json:"enabled,omitempty"`
	// Number of days before the expiration date an SSL certificate will be considered 'expiring.'
	DaysPriorToExpiration *int `json:"daysPriorToExpiration,omitempty"`
	//   Use this option to limit the certificate expiration check to only the first certificate in the chain (normally the host certificate).
	//   This way you will not be warned about impending expiration of intermediate or root Certification Authority certificates in the chain.
	//   This option does not affect any other certificate validity checks besides expiration.
	//   If omitted, the previous setting will stay in effect. If there is no previous setting, the value will default to false.
	IgnoreIntermediateCertificates *bool `json:"ignoreIntermediateCertificates,omitempty"`
}

func (o *DemGetWebsiteResponseSsl) GetEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.Enabled
}

func (o *DemGetWebsiteResponseSsl) GetDaysPriorToExpiration() *int {
	if o == nil {
		return nil
	}
	return o.DaysPriorToExpiration
}

func (o *DemGetWebsiteResponseSsl) GetIgnoreIntermediateCertificates() *bool {
	if o == nil {
		return nil
	}
	return o.IgnoreIntermediateCertificates
}

// DemGetWebsiteResponseAvailabilityCheckSettings -   Use this field to configure availability tests for the website.
//
//	You are required to configure at least availability monitoring or real user monitoring to be able to create website.
type DemGetWebsiteResponseAvailabilityCheckSettings struct {
	// Configure cloud platforms of the synthetic availability test probes. If omitted or set to null, no particular cloud platform will be enforced.
	PlatformOptions *DemGetWebsiteResponsePlatformOptions `json:"platformOptions,omitempty"`
	//   Configure locations of the synthetic availability test probes.
	//   Acceptable values depend on the selected type and actual values of existing probes.
	TestFrom DemTestFrom `json:"testFrom"`
	// Configure how often availability tests should be performed. Provide a number of seconds that is one of 60, 300, 600, 900, 1800, 3600, 7200, 14400.
	TestIntervalInSeconds float64 `json:"testIntervalInSeconds"`
	//   Default conditions when the entity is considered down.
	//   If omitted or set to null, organization configuration will be used for this entity.
	OutageConfiguration *DemGetWebsiteResponseOutageConfiguration `json:"outageConfiguration,omitempty"`
	//   Use this field to configure whether availability tests should check for presence or absence of a particular string on a page.
	//   If the operator is DOES_NOT_CONTAIN and the value is found on the page, the availability test will fail.
	//   Likewise, if the operator is CONTAINS and the value is not found on the page, the availability test will fail.
	//   If omitted or set to null, the string checking functionality will be disabled.
	CheckForString *DemGetWebsiteResponseCheckForString `json:"checkForString,omitempty"`
	// Configure which protocols need availability tests to be performed. At least one protocol must be provided.
	Protocols []DemWebsiteProtocol `json:"protocols"`
	//   Configure monitoring of SSL/TLS certificates validity. This option is relevant for HTTPS protocol only.
	//   If omitted or set to null, SSL monitoring will be disabled and its previous configuration discarded.
	Ssl *DemGetWebsiteResponseSsl `json:"ssl,omitempty"`
	//   Configure custom request headers to be sent with each availability test. It is possible to provide multiple headers with the same name.
	//   If omitted, set to null or set to an empty array, no custom headers will be sent.
	CustomHeaders []DemCustomHeaders `json:"customHeaders,omitempty"`
	//   Allow insecure SSL renegotiation which introduces a security risk in the communication process.
	//   Checking this option could lead to exposing credentials to unauthorized entities and the possibility of unauthorized access, interception, or manipulation of sensitive data, compromising the integrity and security of the communication channel.
	//   Available only with HTTPS check.
	//   If omitted or set to null, insecure SSL renegotiation won't be allowed.
	AllowInsecureRenegotiation *bool `json:"allowInsecureRenegotiation,omitempty"`
	//   Configure data that will be sent as POST request body by the synthetic probe.
	//   If omitted or set to null/empty string, the probe will send the usual GET requests.
	PostData *string `json:"postData,omitempty"`
}

func (o *DemGetWebsiteResponseAvailabilityCheckSettings) GetPlatformOptions() *DemGetWebsiteResponsePlatformOptions {
	if o == nil {
		return nil
	}
	return o.PlatformOptions
}

func (o *DemGetWebsiteResponseAvailabilityCheckSettings) GetTestFrom() DemTestFrom {
	if o == nil {
		return DemTestFrom{}
	}
	return o.TestFrom
}

func (o *DemGetWebsiteResponseAvailabilityCheckSettings) GetTestIntervalInSeconds() float64 {
	if o == nil {
		return 0.0
	}
	return o.TestIntervalInSeconds
}

func (o *DemGetWebsiteResponseAvailabilityCheckSettings) GetOutageConfiguration() *DemGetWebsiteResponseOutageConfiguration {
	if o == nil {
		return nil
	}
	return o.OutageConfiguration
}

func (o *DemGetWebsiteResponseAvailabilityCheckSettings) GetCheckForString() *DemGetWebsiteResponseCheckForString {
	if o == nil {
		return nil
	}
	return o.CheckForString
}

func (o *DemGetWebsiteResponseAvailabilityCheckSettings) GetProtocols() []DemWebsiteProtocol {
	if o == nil {
		return []DemWebsiteProtocol{}
	}
	return o.Protocols
}

func (o *DemGetWebsiteResponseAvailabilityCheckSettings) GetSsl() *DemGetWebsiteResponseSsl {
	if o == nil {
		return nil
	}
	return o.Ssl
}

func (o *DemGetWebsiteResponseAvailabilityCheckSettings) GetCustomHeaders() []DemCustomHeaders {
	if o == nil {
		return nil
	}
	return o.CustomHeaders
}

func (o *DemGetWebsiteResponseAvailabilityCheckSettings) GetAllowInsecureRenegotiation() *bool {
	if o == nil {
		return nil
	}
	return o.AllowInsecureRenegotiation
}

func (o *DemGetWebsiteResponseAvailabilityCheckSettings) GetPostData() *string {
	if o == nil {
		return nil
	}
	return o.PostData
}

// DemGetWebsiteResponseRum - Use this field to configure real user monitoring (RUM) for the website.
// You are required to configure at least availability monitoring or real user monitoring to be able to create website.
type DemGetWebsiteResponseRum struct {
	ApdexTimeInSeconds *int    `json:"apdexTimeInSeconds,omitempty"`
	Snippet            *string `json:"snippet,omitempty"`
	Spa                bool    `json:"spa"`
}

func (o *DemGetWebsiteResponseRum) GetApdexTimeInSeconds() *int {
	if o == nil {
		return nil
	}
	return o.ApdexTimeInSeconds
}

func (o *DemGetWebsiteResponseRum) GetSnippet() *string {
	if o == nil {
		return nil
	}
	return o.Snippet
}

func (o *DemGetWebsiteResponseRum) GetSpa() bool {
	if o == nil {
		return false
	}
	return o.Spa
}

type DemGetWebsiteResponse struct {
	ID     string                      `json:"id"`
	Type   string                      `json:"type"`
	Status DemGetWebsiteResponseStatus `json:"status"`
	//   Name of the website, which must be unique within the organization.
	//   The website must also not contain any control characters, any white space other than space (U+0020), or any consecutive, leading or trailing spaces.
	Name string `json:"name"`
	// URL of the website. Must be a valid URL with no leading or trailing white space. Must not contain invalid port number (>65535).
	URL string `json:"url"`
	// Defines which monitoring features are enabled for a website.
	MonitoringOptions MonitoringOptions `json:"monitoringOptions"`
	//   Use this field to configure availability tests for the website.
	//   You are required to configure at least availability monitoring or real user monitoring to be able to create website.
	AvailabilityCheckSettings *DemGetWebsiteResponseAvailabilityCheckSettings `json:"availabilityCheckSettings,omitempty"`
	// Entity tags. Tag is a key-value pair, where there may be only single tag value for the same key.
	Tags []CommonTag `json:"tags,omitempty"`
	// Use this field to configure real user monitoring (RUM) for the website.
	// You are required to configure at least availability monitoring or real user monitoring to be able to create website.
	Rum *DemGetWebsiteResponseRum `json:"rum,omitempty"`
	// Time when the last outage started.
	LastOutageStartTime *time.Time `json:"lastOutageStartTime,omitempty"`
	// Time when the last outage ended.
	LastOutageEndTime *time.Time `json:"lastOutageEndTime,omitempty"`
	// Time when the last test was performed.
	LastTestTime *time.Time `json:"lastTestTime,omitempty"`
	// Last time when a synthetic test failed.
	LastErrorTime *time.Time `json:"lastErrorTime,omitempty"`
	// Response time from the last synthetic check in milliseconds.
	LastResponseTime *int `json:"lastResponseTime,omitempty"`
	// Timestamp for when the next on-demand check could be executed. If at '0', it means you can execute it anytime.
	NextOnDemandAvailabilityTime *int `json:"nextOnDemandAvailabilityTime,omitempty"`
}

func (d DemGetWebsiteResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DemGetWebsiteResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *DemGetWebsiteResponse) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *DemGetWebsiteResponse) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

func (o *DemGetWebsiteResponse) GetStatus() DemGetWebsiteResponseStatus {
	if o == nil {
		return DemGetWebsiteResponseStatus("")
	}
	return o.Status
}

func (o *DemGetWebsiteResponse) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *DemGetWebsiteResponse) GetURL() string {
	if o == nil {
		return ""
	}
	return o.URL
}

func (o *DemGetWebsiteResponse) GetMonitoringOptions() MonitoringOptions {
	if o == nil {
		return MonitoringOptions{}
	}
	return o.MonitoringOptions
}

func (o *DemGetWebsiteResponse) GetAvailabilityCheckSettings() *DemGetWebsiteResponseAvailabilityCheckSettings {
	if o == nil {
		return nil
	}
	return o.AvailabilityCheckSettings
}

func (o *DemGetWebsiteResponse) GetTags() []CommonTag {
	if o == nil {
		return nil
	}
	return o.Tags
}

func (o *DemGetWebsiteResponse) GetRum() *DemGetWebsiteResponseRum {
	if o == nil {
		return nil
	}
	return o.Rum
}

func (o *DemGetWebsiteResponse) GetLastOutageStartTime() *time.Time {
	if o == nil {
		return nil
	}
	return o.LastOutageStartTime
}

func (o *DemGetWebsiteResponse) GetLastOutageEndTime() *time.Time {
	if o == nil {
		return nil
	}
	return o.LastOutageEndTime
}

func (o *DemGetWebsiteResponse) GetLastTestTime() *time.Time {
	if o == nil {
		return nil
	}
	return o.LastTestTime
}

func (o *DemGetWebsiteResponse) GetLastErrorTime() *time.Time {
	if o == nil {
		return nil
	}
	return o.LastErrorTime
}

func (o *DemGetWebsiteResponse) GetLastResponseTime() *int {
	if o == nil {
		return nil
	}
	return o.LastResponseTime
}

func (o *DemGetWebsiteResponse) GetNextOnDemandAvailabilityTime() *int {
	if o == nil {
		return nil
	}
	return o.NextOnDemandAvailabilityTime
}
