// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type MetricsCompositeMetric struct {
	// Name of the composite metric.
	Name string `json:"name"`
	// Display name of the composite metric. A short description of the metric.
	DisplayName *string `json:"displayName,omitempty"`
	// Description of the composite metric. A detailed description of the metric.
	Description *string `json:"description,omitempty"`
	// PromQL query to calculate the composite metric.
	Formula string `json:"formula"`
	// Unit of the composite metric.
	Units *string `json:"units,omitempty"`
}

func (o *MetricsCompositeMetric) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *MetricsCompositeMetric) GetDisplayName() *string {
	if o == nil {
		return nil
	}
	return o.DisplayName
}

func (o *MetricsCompositeMetric) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *MetricsCompositeMetric) GetFormula() string {
	if o == nil {
		return ""
	}
	return o.Formula
}

func (o *MetricsCompositeMetric) GetUnits() *string {
	if o == nil {
		return nil
	}
	return o.Units
}
