// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type MetricsGrouping struct {
	Attributes   []CommonKeyValuePair `json:"attributes"`
	Measurements []MetricsMeasurement `json:"measurements"`
}

func (o *MetricsGrouping) GetAttributes() []CommonKeyValuePair {
	if o == nil {
		return []CommonKeyValuePair{}
	}
	return o.Attributes
}

func (o *MetricsGrouping) GetMeasurements() []MetricsMeasurement {
	if o == nil {
		return []MetricsMeasurement{}
	}
	return o.Measurements
}
