// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TokensCreateTokenResponse struct {
	// API token.
	Token string `json:"token"`
}

func (o *TokensCreateTokenResponse) GetToken() string {
	if o == nil {
		return ""
	}
	return o.Token
}
