// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/solarwinds/swo-sdk-go/swov1/internal/utils"
)

// UpdateDatabaseRequestSslMode - SSL mode such as require, verify-ca, verify-full as applicable
type UpdateDatabaseRequestSslMode string

const (
	UpdateDatabaseRequestSslModeRequire    UpdateDatabaseRequestSslMode = "require"
	UpdateDatabaseRequestSslModeVerfifyCa  UpdateDatabaseRequestSslMode = "verfify-ca"
	UpdateDatabaseRequestSslModeVerifyFull UpdateDatabaseRequestSslMode = "verify-full"
)

func (e UpdateDatabaseRequestSslMode) ToPointer() *UpdateDatabaseRequestSslMode {
	return &e
}
func (e *UpdateDatabaseRequestSslMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "require":
		fallthrough
	case "verfify-ca":
		fallthrough
	case "verify-full":
		*e = UpdateDatabaseRequestSslMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpdateDatabaseRequestSslMode: %v", v)
	}
}

// UpdateDatabaseRequestSslOptions - SSL connection options, when sslEnabled is true
type UpdateDatabaseRequestSslOptions struct {
	// SSL mode such as require, verify-ca, verify-full as applicable
	SslMode *UpdateDatabaseRequestSslMode `default:"require" json:"sslMode"`
	// CA file path
	SslCAPath *string `default:"" json:"sslCAPath"`
	// SSL key file path
	SslKeyPath *string `default:"" json:"sslKeyPath"`
	// SSL cert file path
	SslCertPath *string `default:"" json:"sslCertPath"`
}

func (u UpdateDatabaseRequestSslOptions) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateDatabaseRequestSslOptions) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *UpdateDatabaseRequestSslOptions) GetSslMode() *UpdateDatabaseRequestSslMode {
	if o == nil {
		return nil
	}
	return o.SslMode
}

func (o *UpdateDatabaseRequestSslOptions) GetSslCAPath() *string {
	if o == nil {
		return nil
	}
	return o.SslCAPath
}

func (o *UpdateDatabaseRequestSslOptions) GetSslKeyPath() *string {
	if o == nil {
		return nil
	}
	return o.SslKeyPath
}

func (o *UpdateDatabaseRequestSslOptions) GetSslCertPath() *string {
	if o == nil {
		return nil
	}
	return o.SslCertPath
}

// DbConnOptions - Options specifying how plugins connect to database server, authentication method change is not supported
type DbConnOptions struct {
	// Database server host
	Host *string `json:"host,omitempty"`
	// Database server port
	Port *string `json:"port,omitempty"`
	// Encrypted credentials for connecting to database server when using basic auth method (username, password)
	EncryptedCredentials *string `default:"" json:"encryptedCredentials"`
	// Username for connecting to database server needed only for auth methods other than basic auth
	User *string `default:"" json:"user"`
	// Enable ssl when agent connects to database server
	SslEnabled *bool `default:"false" json:"sslEnabled"`
	// SSL connection options, when sslEnabled is true
	SslOptions *UpdateDatabaseRequestSslOptions `json:"sslOptions,omitempty"`
	// Cloud region in case of database managed by cloud provider, required for IAM authentication
	CloudRegion *string `default:"" json:"cloudRegion"`
}

func (d DbConnOptions) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DbConnOptions) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *DbConnOptions) GetHost() *string {
	if o == nil {
		return nil
	}
	return o.Host
}

func (o *DbConnOptions) GetPort() *string {
	if o == nil {
		return nil
	}
	return o.Port
}

func (o *DbConnOptions) GetEncryptedCredentials() *string {
	if o == nil {
		return nil
	}
	return o.EncryptedCredentials
}

func (o *DbConnOptions) GetUser() *string {
	if o == nil {
		return nil
	}
	return o.User
}

func (o *DbConnOptions) GetSslEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.SslEnabled
}

func (o *DbConnOptions) GetSslOptions() *UpdateDatabaseRequestSslOptions {
	if o == nil {
		return nil
	}
	return o.SslOptions
}

func (o *DbConnOptions) GetCloudRegion() *string {
	if o == nil {
		return nil
	}
	return o.CloudRegion
}

type UpdateDatabaseRequest struct {
	// Name for the observed database entity
	Name *string `default:"" json:"name"`
	// Optional advanced configuration options for plugins, e.g. disable-sampling
	ConfigOptions []CommonKeyValuePair `json:"configOptions,omitempty"`
	// Options specifying how plugins connect to database server, authentication method change is not supported
	DbConnOptions *DbConnOptions `json:"dbConnOptions,omitempty"`
	// Tags for observed database entity
	Tags []CommonKeyValuePair `json:"tags,omitempty"`
}

func (u UpdateDatabaseRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateDatabaseRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *UpdateDatabaseRequest) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *UpdateDatabaseRequest) GetConfigOptions() []CommonKeyValuePair {
	if o == nil {
		return nil
	}
	return o.ConfigOptions
}

func (o *UpdateDatabaseRequest) GetDbConnOptions() *DbConnOptions {
	if o == nil {
		return nil
	}
	return o.DbConnOptions
}

func (o *UpdateDatabaseRequest) GetTags() []CommonKeyValuePair {
	if o == nil {
		return nil
	}
	return o.Tags
}
