name: E2E Tests
on:
  pull_request:
    branches:
      - main
    paths:
      - swov1/**
  schedule:
    - cron: '0 2 * * *'  # Run at 2 AM UTC every day
  workflow_dispatch:
jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    container:
      image: golang:1.23-alpine
    env:
      SWO_STAGE_API_TOKEN: ${{ secrets.SWO_STAGE_API_TOKEN }}
      PUBLIC_SWO_API_STAGE_URL: ${{ vars.PUBLIC_SWO_API_STAGE_URL }}
      SLACK_WEBHOOK_URL: ${{ vars.SLACK_WEBHOOK_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Python
        run: |
          apk add --no-cache python3 py3-pip
          python3 -m venv venv
          . venv/bin/activate
          pip install pyyaml
      - name: Replace query time placeholders in YAML
        run: |
          . venv/bin/activate
          python3 replace_env_in_yaml.py swov1/.speakeasy/tests.arazzo.yaml
      - name: Install Speakeasy CLI
        run: |
          wget -q https://github.com/speakeasy-api/speakeasy/releases/download/v1.631.4/speakeasy_linux_amd64.zip
          unzip -o speakeasy_linux_amd64.zip -d /usr/local/bin
          chmod +x /usr/local/bin/speakeasy
      - name: Install curl
        run: apk add --no-cache curl
      - name: Install jq
        run: apk add --no-cache jq
      - name: Run Speakeasy codegen
        env:
          SPEAKEASY_API_KEY: ${{ secrets.SPEAKEASY_API_KEY }}
        run: |
          speakeasy run --minimal
      - name: Run E2E tests and notify Slack (scheduled)
        run: |
          cd swov1
          START_TIME=$(date +%s)
          TEST_OUTPUT=$(go test -v ./tests 2>&1)
          TEST_EXIT_CODE=$?  # Capture exit code immediately after go test
          END_TIME=$(date +%s)
          DURATION=$((END_TIME - START_TIME))
          DURATION_FMT=$(printf "%02d:%02d" $((DURATION/60)) $((DURATION%60)))
          
          TEST_SUMMARY=$(echo "$TEST_OUTPUT" | awk '
          /^=== RUN/ { test=$3 }
          /^--- PASS:/ { print "*" test "* :white_check_mark: PASSED" }
          /^--- FAIL:/ { print "*" test "* :x: FAILED" }
          ')
          
          # Collect errors under each test
          ERRORS=$(echo "$TEST_OUTPUT" | awk '
          /^=== RUN/ { test=$3 }
          /error/ { print "*" test "*:\n```\n" $0 "\n```" }
          ')
        
          if [ $TEST_EXIT_CODE -eq 0 ]; then
            STATUS="PASSED"
          else
            STATUS="FAILED"
          fi
        
          PAYLOAD=$(jq -n --arg summary "$TEST_SUMMARY" --arg errors "$ERRORS" --arg status "$STATUS" --arg duration "$DURATION_FMT" '
            {
              text: "*Nightly SWO SDK GO tests: \($status)*\nDuration: \($duration)\nSee details: https://github.com/solarwinds/swo-sdk-go/actions/runs/18170151433\n\n\($summary)\n\n\($errors)"
            }
          ')
          curl -X POST -H 'Content-type: application/json' --data "$PAYLOAD" $SLACK_WEBHOOK_URL