name: E2E Tests
on:
  pull_request:
    branches:
      - main
    paths:
      - swov1/**
  workflow_dispatch:
jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    container:
      image: golang:1.22-alpine
    env:
      SWO_STAGE_API_TOKEN: ${{ secrets.SWO_STAGE_API_TOKEN }}
      PUBLIC_SWO_API_STAGE_URL: ${{ vars.PUBLIC_SWO_API_STAGE_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set QUERY_START_TIME and QUERY_END_TIME
        id: set_query_times
        run: |
          export QUERY_START_TIME=$(date -u -d '6 hours 1 minute ago' +%Y-%m-%dT%H:%M:%SZ)
          export QUERY_END_TIME=$(date -u -d '1 minute ago' +%Y-%m-%dT%H:%M:%SZ)
          echo "QUERY_START_TIME=$QUERY_START_TIME" >> $GITHUB_ENV
          echo "QUERY_END_TIME=$QUERY_END_TIME" >> $GITHUB_ENV
      - name: Run E2E tests
        run: |
          cd swov1
          go test -v ./tests