name: E2E Tests
on:
  pull_request:
    branches:
      - main
    paths:
      - swov1/**
  schedule:
    - cron: '0 2 * * *'  # Run at 2 AM UTC every day
  workflow_dispatch:
jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    container:
      image: golang:1.22-alpine
    env:
      SWO_STAGE_API_TOKEN: ${{ secrets.SWO_STAGE_API_TOKEN }}
      PUBLIC_SWO_API_STAGE_URL: ${{ vars.PUBLIC_SWO_API_STAGE_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set QUERY_START_TIME and QUERY_END_TIME
        id: set_query_times
        run: |
          export QUERY_START_TIME=$(date -u -d "@$(( $(date +%s) - 6*3600 - 60 ))" +%Y-%m-%dT%H:%M:%SZ)
          export QUERY_END_TIME=$(date -u -d "@$(( $(date +%s) - 60 ))" +%Y-%m-%dT%H:%M:%SZ)
          echo "QUERY_START_TIME=$QUERY_START_TIME" >> $GITHUB_ENV
          echo "QUERY_END_TIME=$QUERY_END_TIME" >> $GITHUB_ENV
      - name: Install Speakeasy CLI
        run: |
          wget -q https://github.com/speakeasy-api/speakeasy/releases/latest/download/speakeasy_linux_amd64.zip
          unzip -o speakeasy_linux_amd64.zip -d /usr/local/bin
          chmod +x /usr/local/bin/speakeasy
      - name: Run Speakeasy codegen
        run: |
          speakeasy run --minimal --skip-compile
      - name: Run E2E tests
        run: |
          cd swov1
          go test -v ./tests