name: E2E Tests
on:
  pull_request:
    branches:
      - main
    paths:
      - swov1/**
  workflow_dispatch:
jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    container:
      image: golang:1.22-alpine
    env:
      SWO_STAGE_API_TOKEN: ${{ secrets.SWO_STAGE_API_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run E2E tests
        run: |
          cd swov1
          go test -v ./tests