name: Generate
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write
  id-token: write
"on":
  workflow_dispatch:
    inputs:
      force:
        description: Force generation of SDKs
        type: boolean
        default: false
      set_version:
        description: optionally set a specific SDK version
        type: string
  schedule:
    - cron: 0 0 * * *
jobs:
  pre-generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set QUERY_START_TIME and QUERY_END_TIME
        id: set_query_times
        run: |
          export QUERY_START_TIME=$(date -u -d "@$(( $(date +%s) - 6*3600 - 60 ))" +%Y-%m-%dT%H:%M:%SZ)
          export QUERY_END_TIME=$(date -u -d "@$(( $(date +%s) - 60 ))" +%Y-%m-%dT%H:%M:%SZ)
          echo "QUERY_START_TIME=$QUERY_START_TIME" >> $GITHUB_ENV
          echo "QUERY_END_TIME=$QUERY_END_TIME" >> $GITHUB_ENV
      - name: Install Python
        run: |
          sudo apt-get update
          sudo apt-get install -y python3
      - name: Replace query time placeholders in YAML
        run: |
          python3 replace_env_in_yaml.py swov1/.speakeasy/tests.arazzo.yaml
        env:
          QUERY_START_TIME: ${{ env.QUERY_START_TIME }}
          QUERY_END_TIME: ${{ env.QUERY_END_TIME }}
  generate:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/workflow-executor.yaml@v15
    with:
      force: ${{ github.event.inputs.force }}
      mode: pr
      set_version: ${{ github.event.inputs.set_version }}
      speakeasy_version: latest
      target: swov1
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}