name: Generate
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write
  id-token: write
"on":
  workflow_dispatch:
    inputs:
      force:
        description: Force generation of SDKs
        type: boolean
        default: false
      set_version:
        description: optionally set a specific SDK version
        type: string
  schedule:
    - cron: 0 0 * * *
jobs:
  set-query-times:
    runs-on: ubuntu-latest
    outputs:
      start: ${{ steps.set-times.outputs.start }}
      end: ${{ steps.set-times.outputs.end }}
    steps:
      - id: set-times
        run: |
          echo "start=$(date -u -d "@$(( $(date +%s) - 6*3600 - 60 ))" +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_OUTPUT
          echo "end=$(date -u -d "@$(( $(date +%s) - 60 ))" +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_OUTPUT
  generate:
    needs: set-query-times
    uses: speakeasy-api/sdk-generation-action/.github/workflows/workflow-executor.yaml@v15
    with:
      force: ${{ github.event.inputs.force }}
      mode: pr
      set_version: ${{ github.event.inputs.set_version }}
      speakeasy_version: latest
      target: swov1
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
  upload-generated:
    needs: generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Upload generated files
        uses: actions/upload-artifact@v4
        with:
          name: generated-files
          path: swov1/
  call-e2e-tests:
    needs: [upload-generated, set-query-times]
    uses: ./.github/workflows/e2e_test.yaml
    secrets:
      SWO_STAGE_API_TOKEN: ${{ secrets.SWO_STAGE_API_TOKEN }}
    with:
      PUBLIC_SWO_API_STAGE_URL: ${{ vars.PUBLIC_SWO_API_STAGE_URL }}
      QUERY_START_TIME: ${{ needs.set-query-times.outputs.start }}
      QUERY_END_TIME: ${{ needs.set-query-times.outputs.end }}
